import { auth, db } from "./firebase-config.js";
import { construirRegistrosResumen, consultarColeccionEmpresa } from "./asistencia/resumen-asistencia.js?v=20260819-4";
import {
  Timestamp, addDoc, collection, doc, getDocs, query, serverTimestamp,
  setDoc, updateDoc, where, writeBatch,
} from "https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js";

const COLECCIONES_BASE = [
  "colaboradores","marcaciones","asignacionesHorarios","horarios","excepcionesHorarios",
  "ajustesAsistenciaDiaria","aprobacionesHorasExtra","permisos","feriados",
  "descansosSustitutoriosFeriados","regularizacionesAsistencia","cierresAsistencia",
  "sucursales","areas","subareas","accesosMoviles","solicitudesDispositivoMovil",
  "companias","anunciosEmpresa","plantillasReportes","incidenciasAsistencia",
  "auditoriaSistema","historialOperacionesAsistencia","cierresDiariosAutomaticos",
];
const COLECCIONES_RESPALDO = COLECCIONES_BASE.filter((n)=>!['auditoriaSistema','historialOperacionesAsistencia'].includes(n));
const COLUMNAS_PLANILLA = {
  documento:"Documento",colaborador:"Colaborador",sucursal:"Sucursal",area:"Área",subarea:"Subárea",
  diasProgramados:"Días programados",diasTrabajados:"Días trabajados",ausencias:"Faltas",
  tardanzas:"Tardanzas",minutosTardanza:"Minutos tardanza",permisos:"Permisos",
  horasTrabajadas:"Horas trabajadas",horasAusencia:"Horas ausencia",extraGenerada:"Extra generada",
  extraPendiente:"Extra pendiente",extraAprobada:"Extra aprobada",
};
const COLUMNAS_DEFECTO = Object.keys(COLUMNAS_PLANILLA);
let datos = {}, control, calendarioFecha = new Date(), mapa, capasMapa = [];
let cierreProgramado = false;

export function iniciarCentroControl(){
  control?.abort(); control=new AbortController(); const o={signal:control.signal};
  if(!document.querySelector('.centro-control'))return;
  document.querySelector('.cc-tabs')?.addEventListener('click',cambiarTab,o);
  document.getElementById('ccActualizar')?.addEventListener('click',cargar,o);
  document.getElementById('ccFiltroAlerta')?.addEventListener('change',renderAlertas,o);
  document.getElementById('ccFiltroPendiente')?.addEventListener('change',renderPendientes,o);
  document.getElementById('ccCuerpoPendientes')?.addEventListener('click',accionPendiente,o);
  document.getElementById('ccCalcularAnalitica')?.addEventListener('click',calcularAnalitica,o);
  document.getElementById('ccCalendarioAnterior')?.addEventListener('click',()=>moverCalendario(-1),o);
  document.getElementById('ccCalendarioSiguiente')?.addEventListener('click',()=>moverCalendario(1),o);
  document.getElementById('ccCalendarioHoy')?.addEventListener('click',()=>{calendarioFecha=new Date();renderCalendario();},o);
  document.getElementById('ccExportarPlanilla')?.addEventListener('click',exportarPlanilla,o);
  document.getElementById('ccEjecutarCierre')?.addEventListener('click',()=>ejecutarCierreAutomatico(true),o);
  document.getElementById('ccFiltroMapa')?.addEventListener('change',renderMapa,o);
  document.getElementById('ccListaSucursales')?.addEventListener('click',configurarSucursal,o);
  document.getElementById('ccFormAnuncio')?.addEventListener('submit',guardarAnuncio,o);
  document.getElementById('ccListaAnuncios')?.addEventListener('click',accionAnuncio,o);
  document.getElementById('ccFormPlantilla')?.addEventListener('submit',guardarPlantilla,o);
  document.getElementById('ccListaPlantillas')?.addEventListener('click',accionPlantilla,o);
  document.getElementById('ccExportarRespaldo')?.addEventListener('click',exportarRespaldo,o);
  document.getElementById('ccArchivoRespaldo')?.addEventListener('change',validarArchivoRespaldo,o);
  document.getElementById('ccRestaurarRespaldo')?.addEventListener('click',restaurarRespaldo,o);
  document.querySelector('[data-ir-auditoria]')?.addEventListener('click',()=>document.querySelector('.item[data-vista="auditoria"]')?.click(),o);
  prepararFechas(); prepararColumnas(); cargar();
}

export function programarCierreAutomatico(){
  if(cierreProgramado)return; cierreProgramado=true;
  setTimeout(()=>ejecutarCierreAutomatico(false).catch(console.warn),2500);
  const programar=()=>{const ahora=new Date(),proximo=new Date();proximo.setHours(23,59,40,0);if(proximo<=ahora)proximo.setDate(proximo.getDate()+1);setTimeout(async()=>{await ejecutarCierreFecha(fechaISO(new Date()));programar();},proximo-ahora);};
  programar();
}

async function cargar(){
  const empresaId=sessionStorage.getItem('empresaId'); if(!empresaId)return;
  mostrarCarga(true);
  try{
    const resultados=await Promise.all(COLECCIONES_BASE.map(n=>consultarSeguro(n,empresaId)));
    datos=Object.fromEntries(COLECCIONES_BASE.map((n,i)=>[n,resultados[i]]));
    datos.hoy=construirDia(fechaISO(new Date()));
    prepararAlertas(); prepararPendientes(); renderAlertas(); renderPendientes(); renderCalendario(); renderAnuncios(); renderPlantillas(); renderSucursales(); renderBitacora(); renderEstadoCierre();
    await calcularAnalitica();
    texto('ccUltimaActualizacion',`Actualizado ${new Date().toLocaleTimeString('es-PE',{hour:'2-digit',minute:'2-digit'})}`);
  }catch(e){console.error(e);aviso('No se pudo cargar el centro de control',e.message,'error');}
  finally{mostrarCarga(false);}
}

async function consultarSeguro(nombre,empresaId){try{return await consultarColeccionEmpresa(nombre,empresaId);}catch(e){console.warn(nombre,e);return[];}}
function construirDia(fecha){return construirRegistrosResumen({fecha,colaboradores:datos.colaboradores||[],marcaciones:datos.marcaciones||[],asignaciones:datos.asignacionesHorarios||[],horarios:datos.horarios||[],excepciones:datos.excepcionesHorarios||[],ajustesAsistencia:datos.ajustesAsistenciaDiaria||[],aprobacionesHorasExtra:datos.aprobacionesHorasExtra||[],permisos:datos.permisos||[],feriados:datos.feriados||[],descansosSustitutorios:datos.descansosSustitutoriosFeriados||[]});}

function prepararAlertas(){
  const hoy=fechaISO(new Date()),limite=fechaISO(sumarDias(new Date(),7)); const lista=[];
  const tardanzas=(datos.hoy||[]).filter(r=>/TARDANZA/.test(r.estado));
  const ausencias=(datos.hoy||[]).filter(r=>r.estado==='AUSENTE');
  const incompletos=(datos.hoy||[]).filter(r=>/INCOMPLETO/.test(r.estado));
  tardanzas.forEach(r=>lista.push(alerta('ASISTENCIA','Tardanza',r.nombre,`${r.tardanzaMinutos||0} minutos · ${hoy}`,'clock-history')));
  ausencias.forEach(r=>lista.push(alerta('ASISTENCIA','Ausencia',r.nombre,`Sin marcaciones · ${hoy}`,'person-x',true)));
  incompletos.forEach(r=>lista.push(alerta('ASISTENCIA','Jornada incompleta',r.nombre,`Falta una marcación · ${hoy}`,'exclamation-diamond',true)));
  const permisosVencer=(datos.permisos||[]).filter(p=>String(p.estado).toUpperCase()==='APROBADO'&&fechaDato(p.fechaFin||p.fecha)<=limite&&fechaDato(p.fechaFin||p.fecha)>=hoy);
  permisosVencer.forEach(p=>lista.push(alerta('PERMISO','Permiso por finalizar',nombreDato(p),`Finaliza ${fechaVisible(fechaDato(p.fechaFin||p.fecha))}`,'calendar2-minus')));
  const moviles=(datos.solicitudesDispositivoMovil||[]).filter(s=>s.estado==='PENDIENTE');
  moviles.forEach(s=>lista.push(alerta('MOVIL','Dispositivo pendiente',s.colaboradorNombre||s.nombre||'Colaborador','Solicita autorización móvil','phone')));
  const empresa=(datos.companias||[])[0]||{},fin=fechaDato(empresa.suscripcion?.fechaFin);
  if(fin&&fin<hoy)lista.unshift(alerta('PLAN','Suscripción vencida',empresa.razonSocial||'Empresa',`Venció ${fechaVisible(fin)}`,'credit-card',true));
  datos.alertas=lista; texto('ccTardanzas',tardanzas.length);texto('ccAusencias',ausencias.length);texto('ccIncompletos',incompletos.length);texto('ccPermisosVencer',permisosVencer.length);texto('ccDispositivos',moviles.length);texto('ccPlan',fin&&fin<hoy?'Vencido':empresa.suscripcion?.condicion||'Gratis');texto('ccBadgeAlertas',lista.length);
}
function alerta(tipo,titulo,nombre,detalle,icono,critica=false){return{tipo,titulo,nombre,detalle,icono,critica};}
function renderAlertas(){const tipo=valor('ccFiltroAlerta'),lista=(datos.alertas||[]).filter(a=>!tipo||a.tipo===tipo),c=document.getElementById('ccListaAlertas');if(!c)return;c.innerHTML=lista.length?lista.map(a=>`<div class="cc-item ${a.critica?'critica':''}"><i class="bi bi-${a.icono}"></i><div><strong>${html(a.titulo)} · ${html(a.nombre)}</strong><small>${html(a.detalle)}</small></div><em>${html(a.tipo)}</em></div>`).join(''):'<div class="cc-vacio"><i class="bi bi-check-circle"></i><p>No existen alertas para este filtro.</p></div>';}

function prepararPendientes(){const lista=[];
  (datos.permisos||[]).filter(p=>['PENDIENTE','SOLICITADO'].includes(String(p.estado||p.estadoAprobacion).toUpperCase())).forEach(p=>lista.push({id:p.id,tipo:'PERMISO',nombre:nombreDato(p),fecha:rangoDato(p),detalle:p.tipoPermisoNombre||p.tipo||'Permiso',origen:p}));
  (datos.regularizacionesAsistencia||[]).filter(r=>r.estado==='PENDIENTE').forEach(r=>lista.push({id:r.id,tipo:'REGULARIZACION',nombre:r.colaboradorNombre,fecha:r.fecha,detalle:`${etiqueta(r.tipo)} · ${r.horaNueva||'—'}`,origen:r}));
  (datos.aprobacionesHorasExtra||[]).filter(r=>['','PENDIENTE','SOLICITADO'].includes(String(r.estadoAprobacion||r.decision||'').toUpperCase())).forEach(r=>lista.push({id:r.id,tipo:'EXTRA',nombre:r.colaboradorNombre,fecha:r.fecha,detalle:`${r.minutosCalculados||0} minutos`,origen:r}));
  (datos.solicitudesDispositivoMovil||[]).filter(r=>r.estado==='PENDIENTE').forEach(r=>lista.push({id:r.id,tipo:'MOVIL',nombre:r.colaboradorNombre||r.nombre||'Colaborador',fecha:fechaVisibleTimestamp(r.creadoEn||r.fechaSolicitud),detalle:r.dispositivo?.descripcion||'Nuevo dispositivo',origen:r}));
  datos.pendientes=lista;texto('ccBadgePendientes',lista.length);
}
function renderPendientes(){const tipo=valor('ccFiltroPendiente'),lista=(datos.pendientes||[]).filter(p=>!tipo||p.tipo===tipo),c=document.getElementById('ccCuerpoPendientes');if(!c)return;c.innerHTML=lista.length?lista.map(p=>`<tr><td><strong>${html(etiqueta(p.tipo))}</strong></td><td><strong>${html(p.nombre||'—')}</strong></td><td>${html(p.fecha||'—')}</td><td>${html(p.detalle||'—')}</td><td><span class="cc-estado">PENDIENTE</span></td><td><div class="cc-acciones">${p.tipo==='PERMISO'?`<button class="aprobar" data-aprobar-permiso="${p.id}">Aprobar</button><button class="rechazar" data-rechazar-permiso="${p.id}">Rechazar</button>`:`<button data-abrir-pendiente="${p.id}">Revisar y resolver</button>`}</div></td></tr>`).join(''):'<tr><td colspan="6" class="cc-vacio">No existen solicitudes pendientes.</td></tr>';}
async function accionPendiente(e){const aprobar=e.target.closest('[data-aprobar-permiso]')?.dataset.aprobarPermiso,rechazar=e.target.closest('[data-rechazar-permiso]')?.dataset.rechazarPermiso,abrir=e.target.closest('[data-abrir-pendiente]')?.dataset.abrirPendiente;if(aprobar)return decidirPermiso(aprobar,'APROBADO');if(rechazar)return decidirPermiso(rechazar,'RECHAZADO');if(abrir){const p=datos.pendientes.find(x=>x.id===abrir);if(!p)return;if(p.tipo==='MOVIL')return navegarEmpleados('marcacion-movil');if(p.tipo==='REGULARIZACION')return navegarAsistencia('regularizaciones');return navegarAsistencia('resumen');}}
async function decidirPermiso(id,estado){let motivo='';if(estado==='RECHAZADO'){const r=await Swal.fire({title:'Rechazar permiso',input:'textarea',inputLabel:'Motivo obligatorio',showCancelButton:true,inputValidator:v=>String(v||'').trim().length<5?'Escribe un motivo claro':null});if(!r.isConfirmed)return;motivo=r.value.trim();}else{const r=await Swal.fire({icon:'question',title:'Aprobar permiso',text:'El permiso justificará la asistencia durante el período indicado.',showCancelButton:true,confirmButtonText:'Sí, aprobar'});if(!r.isConfirmed)return;}await updateDoc(doc(db,'permisos',id),{estado,[estado==='APROBADO'?'aprobadoPor':'rechazadoPor']:auth.currentUser?.uid||null,[estado==='APROBADO'?'fechaAprobacion':'fechaRechazo']:serverTimestamp(),motivoRechazo:motivo||null,fechaActualizacion:serverTimestamp()});await registrarOperacion('DECISION_PERMISO',{permisoId:id,decision:estado,motivo});await cargar();aviso(`Permiso ${estado==='APROBADO'?'aprobado':'rechazado'}`,'La decisión quedó registrada.','success');}

async function calcularAnalitica(){if(!(datos.colaboradores||[]).length)return;const mes=valor('ccMesAnalitica')||fechaISO(new Date()).slice(0,7),[y,m]=mes.split('-').map(Number);const actual=acumularPeriodo(new Date(y,m-1,1),new Date(y,m,0));const previo=acumularPeriodo(new Date(y,m-2,1),new Date(y,m-1,0));renderComparacion(actual,previo);renderRanking(actual);}
function acumularPeriodo(desde,hasta){const finHoy=inicioDia(new Date());if(hasta>finHoy)hasta=finHoy;const personas=new Map();let tot={asistencias:0,tardanzas:0,ausencias:0,incompletos:0,trabajados:0,personas};for(let d=inicioDia(desde);d<=hasta;d=sumarDias(d,1)){construirDia(fechaISO(d)).forEach(r=>{const p=personas.get(r.colaboradorId)||{nombre:r.nombre,tardanzas:0,incompletos:0,ausencias:0};if(['PRESENTE','TARDANZA','PRESENTE_CON_PERMISO','TARDANZA_CON_PERMISO'].includes(r.estado))tot.asistencias++;if(/TARDANZA/.test(r.estado)){tot.tardanzas++;p.tardanzas++;}if(r.estado==='AUSENTE'){tot.ausencias++;p.ausencias++;}if(/INCOMPLETO/.test(r.estado)){tot.incompletos++;p.incompletos++;}tot.trabajados+=Number(r.minutosTrabajados||0);personas.set(r.colaboradorId,p);});}return tot;}
function renderComparacion(a,p){const c=document.getElementById('ccComparacionMensual');if(!c)return;const items=[['Asistencias',a.asistencias,p.asistencias,true],['Tardanzas',a.tardanzas,p.tardanzas,false],['Ausencias',a.ausencias,p.ausencias,false],['Incompletos',a.incompletos,p.incompletos,false],['Horas trabajadas',duracion(a.trabajados),duracion(p.trabajados),true]];c.innerHTML=items.map(([n,v,ant,positivo])=>{const vn=typeof v==='number'?v:a.trabajados,an=typeof ant==='number'?ant:p.trabajados,d=vn-an,cl=d===0?'':((d>0)===positivo?'mejora':'alerta');return`<div><span>${n}</span><strong>${v}</strong><small class="${cl}">${d===0?'Sin cambio':`${d>0?'+':''}${typeof v==='number'?d:duracion(Math.abs(d))} vs. mes anterior`}</small></div>`;}).join('');}
function renderRanking(a){const lista=[...a.personas.values()].map(p=>({...p,total:p.tardanzas+p.incompletos})).filter(p=>p.total>0).sort((x,y)=>y.total-x.total),c=document.getElementById('ccRanking');if(!c)return;c.innerHTML=lista.length?lista.slice(0,15).map((p,i)=>`<div><b>${i+1}</b><span><strong>${html(p.nombre)}</strong><small>${p.tardanzas} tardanza(s) · ${p.incompletos} incompleto(s)</small></span><em>${p.total}</em></div>`).join(''):'<div class="cc-vacio">Sin reincidencias en el período.</div>';}

function renderCalendario(){const y=calendarioFecha.getFullYear(),m=calendarioFecha.getMonth();texto('ccCalendarioTitulo',new Intl.DateTimeFormat('es-PE',{month:'long',year:'numeric'}).format(calendarioFecha));const inicio=new Date(y,m,1),primero=sumarDias(inicio,-((inicio.getDay()+6)%7)),c=document.getElementById('ccCalendario');if(!c)return;let h=['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(d=>`<div class="cc-dia-semana">${d}</div>`).join('');for(let i=0;i<42;i++){const d=sumarDias(primero,i),iso=fechaISO(d),eventos=[];(datos.feriados||[]).filter(x=>enRango(iso,x.fechaInicio||x.fecha,x.fechaFin||x.fechaInicio||x.fecha)).forEach(x=>eventos.push(['feriado',x.nombre||x.descripcion||'Feriado']));(datos.permisos||[]).filter(x=>String(x.estado).toUpperCase()==='APROBADO'&&enRango(iso,x.fechaInicio||x.fecha,x.fechaFin||x.fechaInicio||x.fecha)).slice(0,2).forEach(x=>eventos.push(['permiso',`${x.tipoPermisoNombre||x.tipo||'Permiso'} · ${nombreDato(x)}`]));const asignadas=(datos.asignacionesHorarios||[]).filter(x=>enRango(iso,x.fechaInicio,x.fechaFin)).length;if(asignadas)eventos.push(['horario',`${asignadas} asignación(es)`]);h+=`<div class="cc-dia ${d.getMonth()!==m?'fuera':''}"><strong>${d.getDate()}</strong>${eventos.slice(0,3).map(e=>`<span class="cc-evento ${e[0]}" title="${html(e[1])}">${html(e[1])}</span>`).join('')}</div>`;}c.innerHTML=h;}
function moverCalendario(n){calendarioFecha=new Date(calendarioFecha.getFullYear(),calendarioFecha.getMonth()+n,1);renderCalendario();}

async function exportarPlanilla(){const desde=valor('ccPlanillaDesde'),hasta=valor('ccPlanillaHasta');if(!desde||!hasta||desde>hasta)return aviso('Período inválido','Revisa las fechas.','warning');const dias=fechasEntre(desde,hasta);if(dias.length>366)return aviso('Período demasiado amplio','El máximo es 366 días.','warning');const mapa=new Map();dias.forEach(f=>construirDia(f).forEach(r=>{let x=mapa.get(r.colaboradorId)||{documento:r.documento||'',colaborador:r.nombre,sucursal:r.sucursal||'',area:r.area||'',subarea:r.subarea||'',diasProgramados:0,diasTrabajados:0,ausencias:0,tardanzas:0,minutosTardanza:0,permisos:0,horasTrabajadas:0,horasAusencia:0,extraGenerada:0,extraPendiente:0,extraAprobada:0};if(r.horarios?.length)x.diasProgramados++;if(['PRESENTE','TARDANZA','PRESENTE_CON_PERMISO','TARDANZA_CON_PERMISO'].includes(r.estado))x.diasTrabajados++;if(r.estado==='AUSENTE')x.ausencias++;if(/TARDANZA/.test(r.estado)){x.tardanzas++;x.minutosTardanza+=Number(r.tardanzaMinutos||0);}if(r.permisoDia)x.permisos++;x.horasTrabajadas+=Number(r.minutosTrabajados||0);x.horasAusencia+=Number(r.minutosAusencia||0);x.extraGenerada+=Number(r.calculoHorasExtra?.minutosExtraTotal||0);const ap=r.aprobacionHorasExtra;if(ap?.decision==='APROBADO')x.extraAprobada+=Number(ap.minutosAprobados||0);else if(r.calculoHorasExtra?.minutosExtraTotal)x.extraPendiente+=Number(r.calculoHorasExtra.minutosExtraTotal||0);mapa.set(r.colaboradorId,x);}));const plantilla=(datos.plantillasReportes||[]).find(p=>p.id===valor('ccPlanillaPlantilla')),columnas=plantilla?.columnas?.length?plantilla.columnas:COLUMNAS_DEFECTO,filas=[...mapa.values()].map(r=>Object.fromEntries(columnas.map(k=>[COLUMNAS_PLANILLA[k],k.startsWith('horas')||k.startsWith('extra')?minutosExcel(r[k]):r[k]])));try{const mod=await import('https://cdn.jsdelivr.net/npm/xlsx-js-style@1.2.0/+esm'),XLSX=mod.default||mod,libro=XLSX.utils.book_new(),hoja=XLSX.utils.json_to_sheet(filas);estilizarHoja(XLSX,hoja,columnas.length,plantilla?.color||'#1d4ed8');XLSX.utils.book_append_sheet(libro,hoja,'Planillas');XLSX.writeFile(libro,`planilla-${desde}-a-${hasta}.xlsx`);await registrarOperacion('EXPORTACION_PLANILLA',{desde,hasta,cantidad:filas.length,plantilla:plantilla?.nombre||'Estándar'});}catch(e){aviso('No se pudo exportar',e.message,'error');}}
function estilizarHoja(XLSX,hoja,n,color){const rango=XLSX.utils.decode_range(hoja['!ref']||'A1:A1');for(let c=0;c<n;c++){const celda=hoja[XLSX.utils.encode_cell({r:0,c})];if(celda)celda.s={font:{bold:true,color:{rgb:'FFFFFF'}},fill:{fgColor:{rgb:String(color).replace('#','').toUpperCase()}},alignment:{horizontal:'center'}};}hoja['!cols']=Array.from({length:n},()=>({wch:19}));hoja['!autofilter']={ref:XLSX.utils.encode_range({r:0,c:0},{r:rango.e.r,c:rango.e.c})};}

async function ejecutarCierreAutomatico(manual){const ayer=sumarDias(new Date(),-1);const r=await ejecutarCierreFecha(fechaISO(ayer),manual);if(manual){await cargar();aviso('Cierre revisado',`${r.incidencias} incidencia(s) detectada(s) para ${fechaVisible(r.fecha)}.${r.omitido?' El cierre automático ya había sido ejecutado.':''}`,'success');}return r;}
async function ejecutarCierreFecha(fecha,forzar=false){const empresaId=sessionStorage.getItem('empresaId');if(!empresaId)return{fecha,incidencias:0};const cierreId=idSeguro(empresaId,fecha),cierreRef=doc(db,'cierresDiariosAutomaticos',cierreId);if(!forzar){const cierres=await consultarSeguro('cierresDiariosAutomaticos',empresaId);if(cierres.some(c=>c.fecha===fecha))return{fecha,incidencias:0,omitido:true};}const nombres=['colaboradores','marcaciones','asignacionesHorarios','horarios','excepcionesHorarios','ajustesAsistenciaDiaria','aprobacionesHorasExtra','permisos','feriados','descansosSustitutoriosFeriados'],res=await Promise.all(nombres.map(n=>consultarSeguro(n,empresaId))),d=Object.fromEntries(nombres.map((n,i)=>[n,res[i]])),registros=construirRegistrosResumen({fecha,colaboradores:d.colaboradores,marcaciones:d.marcaciones,asignaciones:d.asignacionesHorarios,horarios:d.horarios,excepciones:d.excepcionesHorarios,ajustesAsistencia:d.ajustesAsistenciaDiaria,aprobacionesHorasExtra:d.aprobacionesHorasExtra,permisos:d.permisos,feriados:d.feriados,descansosSustitutorios:d.descansosSustitutoriosFeriados}),incompletos=registros.filter(x=>/INCOMPLETO/.test(x.estado));for(const r of incompletos){const id=idSeguro(empresaId,fecha,r.colaboradorId,'INCOMPLETO');await setDoc(doc(db,'incidenciasAsistencia',id),{empresaId,fecha,colaboradorId:r.colaboradorId,colaboradorNombre:r.nombre,colaboradorDocumento:r.documento||null,tipo:'MARCACION_INCOMPLETA',estado:'PENDIENTE',descripcion:explicarIncompleto(r),origen:'CIERRE_AUTOMATICO',detectadoEn:serverTimestamp(),actualizadoEn:serverTimestamp()},{merge:true});}await setDoc(cierreRef,{empresaId,fecha,estado:'COMPLETADO',incidencias:incompletos.length,ejecutadoEn:serverTimestamp(),ejecutadoPor:auth.currentUser?.uid||'SISTEMA_CLIENTE'},{merge:true});await registrarOperacion('CIERRE_AUTOMATICO_DIARIO',{fecha,incidencias:incompletos.length,forzado:forzar});return{fecha,incidencias:incompletos.length};}
function explicarIncompleto(r){if(r.entrada&&!r.salida)return'Registró entrada, pero no salida';if(!r.entrada&&r.salida)return'Registró salida, pero no entrada';return'Las marcaciones no completan la jornada';}
function renderEstadoCierre(){const fecha=fechaISO(sumarDias(new Date(),-1)),inc=(datos.incidenciasAsistencia||[]).filter(i=>i.fecha===fecha&&i.estado==='PENDIENTE').length;const c=document.getElementById('ccEstadoCierre');if(c)c.innerHTML=`<strong>${inc?`${inc} incidencia(s) pendiente(s)`:'Último día sin incidencias pendientes'}</strong><small> Revisión correspondiente al ${fechaVisible(fecha)}.</small>`;}

async function asegurarLeaflet(){if(window.L)return;if(!document.querySelector('link[data-leaflet]')){const l=document.createElement('link');l.rel='stylesheet';l.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';l.dataset.leaflet='1';document.head.appendChild(l);}await new Promise((ok,ko)=>{const s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.onload=ok;s.onerror=ko;document.head.appendChild(s);});}
async function renderMapa(){const c=document.getElementById('ccMapa');if(!c)return;try{await asegurarLeaflet();if(!mapa){mapa=L.map(c).setView([-12.0464,-77.0428],6);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap'}).addTo(mapa);}capasMapa.forEach(x=>mapa.removeLayer(x));capasMapa=[];const puntos=[],filtro=valor('ccFiltroMapa');if(filtro!=='FUERA'){(datos.sucursales||[]).forEach(s=>{const p=coordenadasSucursal(s);if(!p)return;const radio=radioSucursal(s),circulo=L.circle(p,{radius:radio,color:'#2563eb',weight:2,fillColor:'#3b82f6',fillOpacity:.13}),m=L.marker(p).bindPopup(`<strong>${html(s.nombre)}</strong><br>${html(s.direccion||'Sin dirección')}<br><b>Geocerca: ${radio} m</b>`);circulo.addTo(mapa);m.addTo(mapa);capasMapa.push(circulo,m);puntos.push(p);});}if(filtro!=='SUCURSALES'){(datos.marcaciones||[]).filter(m=>{const u=m.ubicacion||{};return Number.isFinite(Number(u.latitud))&&Number.isFinite(Number(u.longitud))&&(filtro!=='FUERA'||marcacionFuera(m));}).slice(-500).forEach(m=>{const p=[Number(m.ubicacion.latitud),Number(m.ubicacion.longitud)],fuera=marcacionFuera(m),mk=L.circleMarker(p,{radius:6,color:fuera?'#dc2626':'#16a34a',fillOpacity:.8}).bindPopup(`<strong>${html(m.colaboradorNombre||'Marcación')}</strong><br>${html(m.fecha||'')} ${html(m.hora||'')}<br><b>${fuera?'Fuera de zona':'Dentro de zona'}</b><br>${html(m.ubicacion?.direccion||m.direccionCompleta||'')}`);mk.addTo(mapa);capasMapa.push(mk);puntos.push(p);});}if(puntos.length)mapa.fitBounds(puntos,{padding:[30,30],maxZoom:16});setTimeout(()=>mapa.invalidateSize(),100);}catch(e){c.innerHTML='<div class="cc-vacio">No se pudo cargar el mapa. Revisa la conexión.</div>';}}
function renderSucursales(){const c=document.getElementById('ccListaSucursales');if(!c)return;c.innerHTML=(datos.sucursales||[]).map(s=>{const p=coordenadasSucursal(s);return`<div class="cc-sucursal"><strong>${html(s.nombre||'Sucursal')}</strong><small>${html(s.direccion||'Sin dirección')}</small><small>${p?`Geocerca configurada · ${radioSucursal(s)} m`:'Sin coordenadas'}</small><button data-config-sucursal="${s.id}">${p?'Editar geocerca':'Configurar ubicación'}</button></div>`;}).join('')||'<div class="cc-vacio">No existen sucursales.</div>';}
async function configurarSucursal(e){const id=e.target.closest('[data-config-sucursal]')?.dataset.configSucursal;if(!id)return;const s=datos.sucursales.find(x=>x.id===id),p=coordenadasSucursal(s)||['',''];const r=await Swal.fire({title:'Geocerca de la sucursal',html:`<input id="ccLat" class="swal2-input" type="number" step="any" placeholder="Latitud" value="${p[0]}"><input id="ccLng" class="swal2-input" type="number" step="any" placeholder="Longitud" value="${p[1]}"><input id="ccRadio" class="swal2-input" type="number" min="20" max="5000" placeholder="Radio permitido (m)" value="${radioSucursal(s)}">`,showCancelButton:true,confirmButtonText:'Guardar geocerca',preConfirm:()=>{const lat=Number(document.getElementById('ccLat').value),lng=Number(document.getElementById('ccLng').value),radio=Number(document.getElementById('ccRadio').value);if(!Number.isFinite(lat)||!Number.isFinite(lng)||!Number.isFinite(radio))return Swal.showValidationMessage('Completa coordenadas y radio válidos.');return{lat,lng,radio};}});if(!r.isConfirmed)return;await updateDoc(doc(db,'sucursales',id),{geocercaMovil:{latitud:r.value.lat,longitud:r.value.lng,radioMetros:r.value.radio},actualizadoEn:serverTimestamp()});await registrarOperacion('CONFIGURACION_GEOCERCA',{sucursalId:id,radioMetros:r.value.radio});await cargar();}
function coordenadasSucursal(s){const lat=Number(s.geocercaMovil?.latitud??s.ubicacion?.latitud??s.latitud??s.coordenadas?.latitud),lng=Number(s.geocercaMovil?.longitud??s.ubicacion?.longitud??s.longitud??s.coordenadas?.longitud);return Number.isFinite(lat)&&Number.isFinite(lng)?[lat,lng]:null;}
function radioSucursal(s){return Number(s.geocercaMovil?.radioMetros??s.geocerca?.radioMetros??s.radioMetros??150)||150;}
function marcacionFuera(m){if(m.ubicacion?.dentroZona===false||m.dentroZona===false)return true;const p=[Number(m.ubicacion?.latitud),Number(m.ubicacion?.longitud)];if(!p.every(Number.isFinite))return false;const suc=(datos.sucursales||[]).find(s=>s.id===(m.sucursalId||m.ubicacion?.sucursalId));const c=coordenadasSucursal(suc||{});if(!c)return false;return distancia(p,c)>radioSucursal(suc||{});}

async function guardarAnuncio(e){e.preventDefault();const empresaId=sessionStorage.getItem('empresaId');await addDoc(collection(db,'anunciosEmpresa'),{empresaId,titulo:valor('ccAnuncioTitulo'),mensaje:valor('ccAnuncioMensaje'),destino:valor('ccAnuncioDestino'),visibleDesde:fechaISO(new Date()),visibleHasta:valor('ccAnuncioHasta'),estado:'PUBLICADO',creadoPor:auth.currentUser?.uid||null,creadoEn:serverTimestamp()});await registrarOperacion('PUBLICACION_ANUNCIO',{titulo:valor('ccAnuncioTitulo'),destino:valor('ccAnuncioDestino')});e.target.reset();prepararFechas();await cargar();aviso('Anuncio publicado','Ya está disponible para los destinatarios.','success');}
function renderAnuncios(){const hoy=fechaISO(new Date()),lista=(datos.anunciosEmpresa||[]).sort((a,b)=>ms(b.creadoEn)-ms(a.creadoEn)),c=document.getElementById('ccListaAnuncios');if(c)c.innerHTML=lista.length?lista.map(a=>`<div class="cc-item"><i class="bi bi-megaphone"></i><div><strong>${html(a.titulo)}</strong><small>${html(a.mensaje)} · Hasta ${fechaVisible(a.visibleHasta)}</small></div><div class="cc-acciones"><button data-alternar-anuncio="${a.id}">${a.estado==='PUBLICADO'?'Desactivar':'Activar'}</button></div></div>`).join(''):'<div class="cc-vacio">No hay anuncios.</div>';const vigente=lista.find(a=>a.estado==='PUBLICADO'&&['TODOS','ADMIN','ADMINISTRADORES'].includes(a.destino)&&a.visibleHasta>=hoy),v=document.getElementById('ccAnuncioVigente');if(v){v.hidden=!vigente;if(vigente)v.innerHTML=`<strong>${html(vigente.titulo)}</strong> · ${html(vigente.mensaje)}`;}}
async function accionAnuncio(e){const id=e.target.closest('[data-alternar-anuncio]')?.dataset.alternarAnuncio;if(!id)return;const a=datos.anunciosEmpresa.find(x=>x.id===id);await updateDoc(doc(db,'anunciosEmpresa',id),{estado:a.estado==='PUBLICADO'?'INACTIVO':'PUBLICADO',actualizadoEn:serverTimestamp()});await cargar();}

function prepararColumnas(){const c=document.getElementById('ccColumnasPlantilla');if(c)c.innerHTML=Object.entries(COLUMNAS_PLANILLA).map(([k,n])=>`<label><input type="checkbox" value="${k}" checked>${n}</label>`).join('');}
async function guardarPlantilla(e){e.preventDefault();const empresaId=sessionStorage.getItem('empresaId'),id=valor('ccPlantillaId'),columnas=[...document.querySelectorAll('#ccColumnasPlantilla input:checked')].map(x=>x.value);if(!columnas.length)return aviso('Selecciona columnas','Elige al menos una columna.','warning');const ref=id?doc(db,'plantillasReportes',id):doc(collection(db,'plantillasReportes'));await setDoc(ref,{empresaId,nombre:valor('ccPlantillaNombre'),encabezado:valor('ccPlantillaEncabezado'),color:valor('ccPlantillaColor'),columnas,actualizadoEn:serverTimestamp(),actualizadoPor:auth.currentUser?.uid||null},{merge:true});e.target.reset();document.getElementById('ccPlantillaColor').value='#1d4ed8';prepararColumnas();await cargar();}
function renderPlantillas(){const lista=datos.plantillasReportes||[],c=document.getElementById('ccListaPlantillas'),s=document.getElementById('ccPlanillaPlantilla');if(c)c.innerHTML=lista.length?lista.map(p=>`<div class="cc-item"><i class="bi bi-layout-text-window"></i><div><strong>${html(p.nombre)}</strong><small>${p.columnas?.length||0} columnas · ${html(p.encabezado||'Sin encabezado')}</small></div><div class="cc-acciones"><button data-usar-plantilla="${p.id}" class="aprobar">Usar y descargar</button><button data-ver-plantilla="${p.id}">Vista previa</button><button data-editar-plantilla="${p.id}">Editar</button></div></div>`).join(''):'<div class="cc-vacio">No hay plantillas.</div>';if(s)s.innerHTML='<option value="">Formato estándar</option>'+lista.map(p=>`<option value="${p.id}">${html(p.nombre)}</option>`).join('');}
function accionPlantilla(e){const usar=e.target.closest('[data-usar-plantilla]')?.dataset.usarPlantilla,ver=e.target.closest('[data-ver-plantilla]')?.dataset.verPlantilla,editar=e.target.closest('[data-editar-plantilla]')?.dataset.editarPlantilla,id=usar||ver||editar;if(!id)return;const p=datos.plantillasReportes.find(x=>x.id===id);if(usar){document.querySelector('[data-cc-tab="planillas"]')?.click();const s=document.getElementById('ccPlanillaPlantilla');if(s)s.value=id;setTimeout(()=>document.getElementById('ccExportarPlanilla')?.scrollIntoView({behavior:'smooth',block:'center'}),80);return;}if(ver){const c=document.getElementById('ccVistaPlantilla');c.innerHTML=`<div class="cc-preview" style="--color:${html(p.color||'#1d4ed8')}"><h4>${html(p.encabezado||p.nombre)}</h4><div class="cc-preview-scroll"><table><tr>${p.columnas.map(k=>`<th>${html(COLUMNAS_PLANILLA[k]||k)}</th>`).join('')}</tr><tr>${p.columnas.map(()=>'<td>Ejemplo</td>').join('')}</tr></table></div><small>Desliza horizontalmente para revisar todas las columnas.</small></div>`;}if(editar){document.getElementById('ccPlantillaId').value=p.id;document.getElementById('ccPlantillaNombre').value=p.nombre||'';document.getElementById('ccPlantillaEncabezado').value=p.encabezado||'';document.getElementById('ccPlantillaColor').value=p.color||'#1d4ed8';document.querySelectorAll('#ccColumnasPlantilla input').forEach(x=>x.checked=p.columnas?.includes(x.value));}}

async function exportarRespaldo(){const empresaId=sessionStorage.getItem('empresaId'),contenido={formato:'CONTROL_ASISTENCIA_BACKUP',version:1,empresaId,creadoEn:new Date().toISOString(),colecciones:{}};const boton=document.getElementById('ccExportarRespaldo');boton.disabled=true;try{for(const n of COLECCIONES_RESPALDO)contenido.colecciones[n]=(await consultarSeguro(n,empresaId)).map(x=>serializar(x));descargarJSON(contenido,`respaldo-control-asistencia-${empresaId}-${fechaISO(new Date())}.json`);await registrarOperacion('EXPORTACION_RESPALDO',{colecciones:Object.keys(contenido.colecciones).length,documentos:Object.values(contenido.colecciones).reduce((s,a)=>s+a.length,0)});aviso('Respaldo creado','Guárdalo en un lugar seguro.','success');}finally{boton.disabled=false;}}
function validarArchivoRespaldo(e){document.getElementById('ccRestaurarRespaldo').disabled=!e.target.files?.[0];}
async function restaurarRespaldo(){const archivo=document.getElementById('ccArchivoRespaldo').files?.[0],empresaId=sessionStorage.getItem('empresaId');if(!archivo)return;let backup;try{backup=JSON.parse(await archivo.text());}catch{return aviso('Archivo inválido','No contiene un JSON válido.','error');}if(backup.formato!=='CONTROL_ASISTENCIA_BACKUP'||backup.empresaId!==empresaId)return aviso('Respaldo no compatible','El archivo no pertenece a esta empresa.','error');const conf=await Swal.fire({icon:'warning',title:'Restaurar respaldo',html:'Se sobrescribirán documentos con el mismo identificador.<br><b>Escribe RESTAURAR para continuar.</b>',input:'text',showCancelButton:true,confirmButtonText:'Restaurar',inputValidator:v=>v!=='RESTAURAR'?'Escribe RESTAURAR exactamente':null});if(!conf.isConfirmed)return;const operaciones=[];for(const[n,docs]of Object.entries(backup.colecciones||{})){if(!COLECCIONES_RESPALDO.includes(n))continue;for(const item of docs||[]){if(!item.id)continue;operaciones.push({ref:doc(db,n,item.id),data:deserializar({...item,id:undefined})});}}for(let i=0;i<operaciones.length;i+=400){const lote=writeBatch(db);operaciones.slice(i,i+400).forEach(o=>lote.set(o.ref,o.data,{merge:true}));await lote.commit();}await registrarOperacion('RESTAURACION_RESPALDO',{documentos:operaciones.length,archivo:archivo.name});await cargar();aviso('Restauración completada',`${operaciones.length} documentos fueron procesados.`,'success');}
function renderBitacora(){const lista=[...(datos.auditoriaSistema||[]),...(datos.historialOperacionesAsistencia||[])].sort((a,b)=>ms(b.fecha||b.creadoEn)-ms(a.fecha||a.creadoEn)).slice(0,15),c=document.getElementById('ccBitacora');if(c)c.innerHTML=lista.length?lista.map(x=>`<div class="cc-item"><i class="bi bi-shield-check"></i><div><strong>${html(x.resumen||etiqueta(x.tipo||x.accion||'Operación'))}</strong><small>${html(x.responsableNombre||x.usuarioEmail||'Usuario')} · ${fechaVisibleTimestamp(x.fecha||x.creadoEn)}</small></div></div>`).join(''):'<div class="cc-vacio">Sin operaciones registradas.</div>';}
async function registrarOperacion(tipo,detalle={}){const empresaId=sessionStorage.getItem('empresaId');if(!empresaId)return;await addDoc(collection(db,'historialOperacionesAsistencia'),{empresaId,tipo,...detalle,usuarioId:auth.currentUser?.uid||null,usuarioEmail:auth.currentUser?.email||null,fecha:serverTimestamp()});}

function cambiarTab(e){const b=e.target.closest('[data-cc-tab]');if(!b)return;document.querySelectorAll('[data-cc-tab]').forEach(x=>x.classList.toggle('activo',x===b));document.querySelectorAll('[data-cc-panel]').forEach(x=>x.classList.toggle('activo',x.dataset.ccPanel===b.dataset.ccTab));if(b.dataset.ccTab==='mapa')setTimeout(renderMapa,50);}
function prepararFechas(){const hoy=new Date(),desde=new Date(hoy.getFullYear(),hoy.getMonth(),1);if(document.getElementById('ccMesAnalitica'))document.getElementById('ccMesAnalitica').value=fechaISO(hoy).slice(0,7);if(document.getElementById('ccPlanillaDesde'))document.getElementById('ccPlanillaDesde').value=fechaISO(desde);if(document.getElementById('ccPlanillaHasta'))document.getElementById('ccPlanillaHasta').value=fechaISO(hoy);if(document.getElementById('ccAnuncioHasta'))document.getElementById('ccAnuncioHasta').value=fechaISO(sumarDias(hoy,7));}
function mostrarCarga(v){const e=document.getElementById('ccCarga');if(e)e.hidden=!v;}
function navegarEmpleados(tab){document.querySelector('.item[data-vista="empleados"]')?.click();esperar(()=>document.querySelector(`.tab[data-tab="${tab}"]`)?.click());}
function navegarAsistencia(tab){document.querySelector('.item[data-vista="asistencia"]')?.click();esperar(()=>document.querySelector(`.asistencia-tab[data-tab="${tab}"]`)?.click());}
function esperar(fn,n=0){if(fn())return;if(n<30)setTimeout(()=>esperar(fn,n+1),100);}
function aviso(t,m,i='info'){return window.Swal?Swal.fire({title:t,text:m,icon:i,confirmButtonColor:'#2563eb'}):alert(`${t}\n${m}`);}
function valor(id){return String(document.getElementById(id)?.value||'').trim();}function texto(id,v){const e=document.getElementById(id);if(e)e.textContent=v;}
function html(v){const e=document.createElement('div');e.textContent=String(v??'');return e.innerHTML;}function etiqueta(v){return String(v||'').replaceAll('_',' ').toLowerCase().replace(/(^|\s)\S/g,l=>l.toUpperCase());}
function inicioDia(d){return new Date(d.getFullYear(),d.getMonth(),d.getDate());}function sumarDias(d,n){const r=inicioDia(d);r.setDate(r.getDate()+n);return r;}function fechaISO(d){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function fechaDato(v){if(!v)return'';if(v?.toDate)return fechaISO(v.toDate());return String(v).slice(0,10);}function fechaVisible(v){if(!v)return'—';const[y,m,d]=String(v).slice(0,10).split('-').map(Number);return new Intl.DateTimeFormat('es-PE').format(new Date(y,m-1,d));}function fechaVisibleTimestamp(v){if(!v)return'—';const d=v?.toDate?v.toDate():new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('es-PE');}
function rangoDato(x){const a=fechaDato(x.fechaInicio||x.fecha),b=fechaDato(x.fechaFin||x.fechaInicio||x.fecha);return a===b?fechaVisible(a):`${fechaVisible(a)} al ${fechaVisible(b)}`;}function enRango(f,a,b){a=fechaDato(a);b=fechaDato(b||a);return a&&f>=a&&f<=b;}function nombreDato(x){return x.colaboradorNombre||x.nombreColaborador||x.nombre||x.datosPersonales&&[x.datosPersonales.nombres,x.datosPersonales.apellidos].filter(Boolean).join(' ')||'Colaborador';}
function fechasEntre(a,b){const r=[];for(let d=new Date(`${a}T00:00:00`);d<=new Date(`${b}T00:00:00`);d=sumarDias(d,1))r.push(fechaISO(d));return r;}function duracion(v){v=Math.max(0,Math.round(Number(v)||0));return`${Math.floor(v/60)} h${v%60?` ${v%60} min`:''}`;}function minutosExcel(v){v=Math.max(0,Math.round(Number(v)||0));return`${String(Math.floor(v/60)).padStart(2,'0')}:${String(v%60).padStart(2,'0')}`;}function idSeguro(...x){return x.join('_').replace(/[^a-zA-Z0-9_-]/g,'_');}function ms(v){return v?.toMillis?v.toMillis():new Date(v||0).getTime()||0;}
function distancia(a,b){const R=6371000,p=x=>x*Math.PI/180,d1=p(b[0]-a[0]),d2=p(b[1]-a[1]),q=Math.sin(d1/2)**2+Math.cos(p(a[0]))*Math.cos(p(b[0]))*Math.sin(d2/2)**2;return 2*R*Math.atan2(Math.sqrt(q),Math.sqrt(1-q));}
function descargarJSON(obj,nombre){const url=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=nombre;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function serializar(v){if(v?.toDate)return{__tipo:'timestamp',segundos:v.seconds,nanosegundos:v.nanoseconds};if(Array.isArray(v))return v.map(serializar);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,serializar(x)]));return v;}
function deserializar(v){if(v&&v.__tipo==='timestamp')return new Timestamp(v.segundos,v.nanosegundos||0);if(Array.isArray(v))return v.map(deserializar);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).filter(([,x])=>x!==undefined).map(([k,x])=>[k,deserializar(x)]));return v;}
