const SECCIONES_MANUAL=[
 {id:"inicio",icono:"bi-house",titulo:"Primeros pasos",texto:"Ingresa con tu cuenta, revisa el Dashboard y utiliza la barra lateral en computadora o la barra inferior en celular. El nombre de la vista activa aparece en la parte superior. Desde el avatar puedes actualizar tus datos y contraseña.",pasos:["Usa la fecha del Dashboard para consultar otro día.","Mantén presionado un icono móvil para ver su nombre.","Los cambios importantes quedan registrados en Auditoría."]},
 {id:"dashboard",icono:"bi-speedometer2",titulo:"Dashboard",texto:"Presenta el estado operativo del día y el acumulado mensual. Las tarjetas superiores son interactivas y muestran qué colaboradores integran cada resultado.",pasos:["Filtra por sucursal, área o subárea.","Abre colaboradores activos, asistencias, tardanzas, ausencias, incompletos u horas extra pendientes.","Usa Configuración pendiente para identificar personal sin horario o ubicación y resolverlo rápidamente.","Los accesos rápidos llevan a Asistencia, Empleados, Horarios y Auditoría."]},
 {id:"compania",icono:"bi-building",titulo:"Compañía",texto:"Centraliza la información organizacional utilizada por los demás módulos.",pasos:["Información: registra datos generales de la empresa y representante.","Sucursales: crea y administra centros de trabajo.","Áreas: organiza las unidades funcionales.","Subáreas: completa la estructura interna asociándolas a su área."]},
 {id:"empleados",icono:"bi-people",titulo:"Empleados y colaboradores",texto:"Administra al personal, sus horarios, permisos y feriados.",pasos:["Colaboradores: crear, buscar, modificar, activar, desactivar o eliminar personal.","Horarios: crear jornadas y asignarlas de forma diaria, semanal o mensual.","Permisos: seleccionar colaborador, periodo, motivo, sustento y estado.","Feriados: configurar fechas especiales, descansos y tratamiento de marcaciones.","La búsqueda de personas se muestra por apellidos y nombres."]},
 {id:"horarios",icono:"bi-calendar-week",titulo:"Asignación de horarios",texto:"Permite programar la jornada que corresponde a cada colaborador sin repetir reglas en Configuración.",pasos:["Diaria: aplica una jornada a una fecha específica.","Semanal: configura uno o varios patrones semanales y el periodo de repetición.","Mensual: planifica días concretos dentro del calendario.","Antes de guardar, revisa colaborador, horario, fechas y días seleccionados.","Las asignaciones y modificaciones se registran en Auditoría."]},
 {id:"asistencia",icono:"bi-clock-history",titulo:"Asistencia",texto:"Consulta y administra las marcaciones y resultados diarios o mensuales.",pasos:["Resumen diario: navega por fecha, filtra y revisa el estado de cada colaborador.","Recalcular: vuelve a consultar y reconstruye los resultados del día.","Registrar marcación: elige colaborador y tipo; luego ingresa hora y motivo.","Ver: abre el detalle diario legible.","Importar: carga marcaciones desde Excel o CSV.","Ver historial: abre la pestaña Marcaciones.","Resumen mensual: consulta periodos, revisa detalles y exporta reportes.","Incidencias, regularizaciones y cierres agrupan los procesos de control posteriores."]},
 {id:"auditoria",icono:"bi-share",titulo:"Auditoría global",texto:"Muestra la trazabilidad de los cambios realizados en todo el sistema con lenguaje comprensible.",pasos:["Busca por responsable, persona afectada, módulo o contenido.","Filtra por acción y rango de fechas.","Abre el ojo para conocer quién realizó el cambio, a quién afectó, qué cambió y cuándo.","Las altas, modificaciones, activaciones, desactivaciones, eliminaciones y asignaciones conservan su detalle."]},
 {id:"configuracion",icono:"bi-gear",titulo:"Configuración",texto:"Contiene únicamente preferencias generales que no duplican reglas de horarios o asistencia.",pasos:["Apariencia: selecciona color, densidad y vista inicial del dispositivo.","Información del sistema: consulta versión, empresa, usuario, conexión y entorno.","Restaurar devuelve la apariencia recomendada."]},
 {id:"movil",icono:"bi-phone",titulo:"Uso desde celular",texto:"La interfaz móvil utiliza una navegación inferior fija y formularios adaptados.",pasos:["Desplázate dentro de los formularios; sus botones permanecen accesibles.","Al abrir un modal, este se muestra por encima de la navegación.","Cierra el modal con X, Cancelar o la acción correspondiente.","Si una actualización no aparece, cierra completamente la pestaña y vuelve a abrirla."]},
 {id:"ayuda",icono:"bi-life-preserver",titulo:"Problemas frecuentes",texto:"Comprobaciones sencillas antes de solicitar soporte.",pasos:["Confirma que exista conexión a Internet.","Verifica que el colaborador tenga ubicación y horario asignados.","Revisa la fecha seleccionada y los filtros activos.","Si una importación falla, valida columnas, DNI y formato de fecha/hora.","Consulta Auditoría para confirmar si el cambio fue guardado."]}
];

let modal;
export function iniciarManual(){
 if(document.getElementById("modalManualSistema"))return;
 modal=document.createElement("div");modal.id="modalManualSistema";modal.className="modal-manual-sistema";modal.hidden=true;modal.setAttribute("aria-hidden","true");
 modal.innerHTML=`<article><header><div><span>CENTRO DE AYUDA</span><h2>Manual del sistema</h2><p>Guía completa de Control de Asistencia</p></div><button type="button" id="cerrarManualSistema" aria-label="Cerrar"><i class="bi bi-x-lg"></i></button></header><div class="manual-herramientas"><i class="bi bi-search"></i><input id="buscarManualSistema" type="search" placeholder="Buscar una función, botón o módulo…"></div><div class="manual-layout"><nav>${SECCIONES_MANUAL.map((s,i)=>`<button type="button" data-manual="${s.id}" class="${i===0?"activo":""}"><i class="bi ${s.icono}"></i><span>${s.titulo}</span></button>`).join("")}</nav><main id="contenidoManualSistema"></main></div></article>`;
 document.body.appendChild(modal);
 modal.querySelector("#cerrarManualSistema").addEventListener("click",cerrarManual);
 modal.addEventListener("click",e=>{if(e.target===modal)cerrarManual();const b=e.target.closest("[data-manual]");if(b)mostrarSeccion(b.dataset.manual);});
 modal.querySelector("#buscarManualSistema").addEventListener("input",e=>buscarManual(e.target.value));
 mostrarSeccion("inicio");
}
export function abrirManual(){if(!modal)iniciarManual();modal.hidden=false;modal.setAttribute("aria-hidden","false");document.body.classList.add("manual-abierto");setTimeout(()=>modal.querySelector("#buscarManualSistema")?.focus(),30);}
function cerrarManual(){modal.hidden=true;modal.setAttribute("aria-hidden","true");document.body.classList.remove("manual-abierto");}
function mostrarSeccion(id){const s=SECCIONES_MANUAL.find(x=>x.id===id)||SECCIONES_MANUAL[0];modal.querySelectorAll("[data-manual]").forEach(b=>b.classList.toggle("activo",b.dataset.manual===s.id));modal.querySelector("#contenidoManualSistema").innerHTML=`<section class="manual-seccion"><div class="manual-icono"><i class="bi ${s.icono}"></i></div><span>GUÍA DEL MÓDULO</span><h3>${s.titulo}</h3><p>${s.texto}</p><ol>${s.pasos.map(p=>`<li>${p}</li>`).join("")}</ol></section>`;}
function buscarManual(valor){const q=String(valor||"").trim().toLocaleLowerCase("es");if(!q){mostrarSeccion("inicio");return;}const encontrados=SECCIONES_MANUAL.filter(s=>`${s.titulo} ${s.texto} ${s.pasos.join(" ")}`.toLocaleLowerCase("es").includes(q));modal.querySelectorAll("[data-manual]").forEach(b=>b.classList.remove("activo"));modal.querySelector("#contenidoManualSistema").innerHTML=encontrados.length?`<div class="manual-resultados"><h3>Resultados (${encontrados.length})</h3>${encontrados.map(s=>`<button type="button" data-manual="${s.id}"><i class="bi ${s.icono}"></i><div><strong>${s.titulo}</strong><span>${s.texto}</span></div></button>`).join("")}</div>`:`<div class="manual-sin-resultados"><i class="bi bi-search"></i><h3>Sin resultados</h3><p>Prueba con asistencia, horarios, empleados, auditoría o marcación.</p></div>`;}
