const SECCIONES_MANUAL=[
 guia("inicio","bi-house","Primeros pasos","Inicio de sesión → Dashboard","Conocer la navegación y preparar el sistema antes de registrar asistencia.",["Cuenta de usuario activa","Empresa registrada"],["Ingresa con tu correo y contraseña.","En computadora utiliza el menú lateral; en celular utiliza la barra inferior fija.","Presiona tu avatar para editar nombre, correo o contraseña.","Abre Manual cuando necesites consultar un procedimiento.","Completa primero Compañía y después registra a los colaboradores."],"El usuario queda dentro del Dashboard y puede navegar según sus permisos.","El orden recomendado es: Compañía → estructura organizacional → colaboradores → horarios → asistencia."),
 guia("dashboard","bi-speedometer2","Dashboard","Menú → Dashboard","Revisar rápidamente el estado diario y el acumulado mensual.",["Colaboradores activos","Horarios asignados"],["Selecciona la fecha de consulta y presiona Actualizar.","Si corresponde, filtra por sucursal, área o subárea.","Presiona una tarjeta superior para ver las personas incluidas en el indicador.","Revisa Alertas del día para identificar ausencias o marcaciones incompletas.","En Configuración pendiente abre Sin horario o Sin ubicación para corregir al personal.","Usa los accesos rápidos para continuar con la gestión necesaria."],"El Dashboard muestra cifras y listas correspondientes a la fecha y filtros elegidos.","Las tarjetas son accesos de consulta; las modificaciones se realizan desde el módulo correspondiente."),
 guia("empresa","bi-building","Datos de la compañía","Compañía → Información","Registrar los datos generales utilizados en pantallas y reportes.",["RUC y razón social","Dirección y datos de contacto"],["Abre Compañía y permanece en Información.","Completa RUC, razón social y giro de negocio.","Registra dirección, departamento, provincia y distrito.","Completa teléfono, correo y demás información disponible.","Revisa los datos y presiona Guardar cambios.","Si administras representantes, agrégalos desde la sección correspondiente."],"La información queda disponible para reportes y datos institucionales.","Evita abreviaturas diferentes a las registradas legalmente en la razón social."),
 guia("sucursales","bi-buildings","Sucursales","Compañía → Sucursales","Crear los centros de trabajo de la empresa.",["Datos de la compañía guardados","Nombre y dirección de la sede"],["Abre la pestaña Sucursales.","Presiona Nueva sucursal.","Ingresa un nombre claro, por ejemplo: Sede Central o Sucursal Mala.","Completa dirección y datos adicionales solicitados.","Verifica el estado inicial y presiona Guardar.","Usa editar para actualizar una sede existente; desactívala si ya no debe utilizarse."],"La sucursal aparece disponible al crear áreas y asignar colaboradores.","No crees dos sucursales para la misma sede; primero utiliza la búsqueda."),
 guia("areas","bi-diagram-3","Áreas","Compañía → Áreas","Organizar las unidades principales de trabajo.",["Al menos una sucursal creada","Nombre oficial del área"],["Abre la pestaña Áreas.","Presiona Nueva área.","Escribe el nombre, por ejemplo Administración, Ventas o Docencia.","Selecciona la sucursal cuando el formulario lo solicite.","Agrega una descripción breve si está disponible.","Presiona Guardar y confirma que aparezca en el listado."],"El área queda disponible para subáreas y colaboradores.","Utiliza nombres uniformes; evita crear Administración y Área Administrativa como registros distintos si representan lo mismo."),
 guia("subareas","bi-bezier2","Subáreas","Compañía → Subáreas","Crear divisiones internas dependientes de un área.",["Sucursal creada","Área creada"],["Abre la pestaña Subáreas.","Presiona Nueva subárea.","Selecciona primero la sucursal.","Selecciona el área a la que pertenecerá.","Escribe el nombre de la subárea.","Guarda y revisa la relación mostrada en el listado."],"La estructura Sucursal → Área → Subárea queda disponible para asignar personal.","Si el selector de área está vacío, revisa primero que la sucursal tenga áreas registradas."),
 guia("colaboradores","bi-person-plus","Colaboradores","Empleados → Colaboradores","Registrar y mantener la ficha completa del personal.",["Sucursal, área y subárea creadas","Documento y datos del colaborador"],["Abre Empleados y selecciona Colaboradores.","Presiona Nuevo colaborador.","En Información general completa apellidos, nombres, documento, fecha de nacimiento, género y contacto.","En Organización selecciona sucursal, área y subárea.","En Información adicional registra cargo, profesión y fechas de contrato.","Revisa los campos obligatorios y presiona Guardar.","Utiliza buscar, editar, activar, desactivar o eliminar según corresponda."],"El colaborador aparece activo y disponible para asignación de horarios y permisos.","Busca primero por apellidos o documento para evitar duplicados."),
 guia("crear-horario","bi-clock","Crear un horario","Empleados → Horarios → Nuevo horario","Definir una jornada reutilizable antes de asignarla.",["Horas de entrada y salida definidas","Regla de refrigerio conocida"],["Abre Horarios y presiona Nuevo horario.","Asigna un nombre reconocible, por ejemplo Horario administrativo.","Registra entrada y salida programadas.","Configura refrigerio cuando corresponda.","Completa tolerancias y reglas propias del horario únicamente en esta vista.","Revisa si cruza medianoche y las ventanas permitidas.","Presiona Guardar horario."],"El horario aparece en el listado y puede asignarse a uno o varios días.","No repitas estas reglas en Configuración; cada jornada conserva sus propios criterios."),
 guia("asignar-horario","bi-calendar-check","Asignar horarios","Empleados → Horarios → Seleccionar horario → Asignar","Programar cuándo se aplicará una jornada a un colaborador.",["Colaborador activo","Horario creado"],["Busca y selecciona el horario que deseas aplicar.","Presiona Asignar y selecciona al colaborador por apellidos y nombres.","Elige Diaria para una fecha específica, Semanal para patrones por día o Mensual para el calendario.","En Semanal agrega horarios a los días correspondientes y configura las semanas del patrón.","Indica Desde y Hasta para repetir el patrón durante el periodo.","En Mensual marca directamente los días del calendario.","Revisa el resumen final y confirma la asignación."],"El colaborador queda programado y el cambio aparece en Auditoría.","Si el periodo termina a mitad de mes, el sistema aplica el patrón solo hasta la fecha final."),
 guia("permisos","bi-file-earmark-check","Permisos","Empleados → Permisos","Registrar una autorización o ausencia justificada del colaborador.",["Colaborador registrado","Fechas, motivo y sustento disponibles"],["Abre Permisos y busca al colaborador.","Selecciona al colaborador y presiona Nuevo permiso.","Elige el tipo de permiso.","Indica fecha de inicio y término; si es por horas, registra hora inicial y final.","Escribe el motivo obligatorio y observaciones necesarias.","Adjunta PDF, JPG o PNG cuando exista sustento.","Selecciona el estado inicial y presiona Guardar permiso."],"El permiso aparece en el calendario y se considera en la evaluación de asistencia.","Verifica cuidadosamente fechas y horas antes de aprobar un permiso."),
 guia("feriados","bi-calendar2-event","Feriados","Empleados → Feriados","Registrar días especiales y definir su tratamiento laboral.",["Fecha oficial confirmada","Criterio laboral definido"],["Abre Feriados y presiona Nuevo feriado.","Ingresa nombre y tipo de fecha especial.","Selecciona fecha de inicio y término.","Activa Descanso remunerado cuando corresponda.","Define si las horas son compensables y si se permitirán marcaciones.","Agrega una descripción u observación.","Guarda y comprueba el evento en el calendario."],"La fecha queda identificada en los cálculos y calendarios del personal.","La configuración debe corresponder a la política de la empresa y a la norma aplicable."),
 guia("diario","bi-calendar-day","Resumen diario","Asistencia → Resumen diario","Consultar el estado individual de asistencia de una fecha.",["Horarios asignados","Marcaciones registradas o importadas"],["Selecciona la fecha con las flechas, el calendario o el botón Hoy.","Busca al colaborador o filtra por ubicación y estado.","Revisa entrada, refrigerio, salida, horas trabajadas, jornada y horas extra.","Presiona Ver para abrir el detalle diario.","Usa Recalcular después de corregir o importar información.","Presiona Registrar marcación para elegir colaborador y tipo de registro."],"El resumen refleja el estado calculado de cada colaborador para el día.","Una marcación incompleta debe revisarse antes del cierre del periodo."),
 guia("marcaciones","bi-fingerprint","Marcaciones e importación","Asistencia → Resumen diario o Marcaciones","Registrar manualmente o importar eventos del reloj.",["Documento del colaborador válido","Fecha y hora correctas"],["Para registro manual presiona Registrar marcación.","Selecciona colaborador y tipo: entrada, inicio/fin de refrigerio o salida.","Presiona Continuar, ingresa la hora real y escribe el motivo.","Confirma con Registrar marcación.","Para carga masiva presiona Importar y selecciona Excel o CSV.","Verifica las columnas de documento y fecha/hora en la vista previa.","Confirma únicamente las filas válidas y revisa luego el historial."],"Las marcaciones se incorporan al cálculo diario y quedan auditadas.","No importes dos veces el mismo archivo sin revisar posibles duplicados."),
 guia("mensual","bi-calendar3","Resumen mensual y reportes","Asistencia → Resumen mensual","Analizar un periodo y generar reportes.",["Periodo con información procesada","Filtros organizacionales definidos"],["Selecciona Desde y Hasta según el periodo de corte.","Aplica filtros de colaborador, sucursal, área o subárea.","Revisa días programados, asistencias, tardanzas, ausencias y permisos.","Comprueba horas asignadas, trabajadas, ausentes y extras.","Presiona Ver detalle para consultar los días de un colaborador.","Utiliza Descargar, elige tipo de reporte y formato.","Revisa la vista previa antes de generar Excel o PDF."],"Se obtiene un reporte del periodo con los datos institucionales y filtros aplicados.","La exportación se realiza aquí; no es necesario exportar desde el resumen diario."),
 guia("auditoria","bi-share","Auditoría global","Menú → Auditoría","Consultar quién realizó cada cambio y qué información fue afectada.",["Operaciones registradas en el sistema"],["Utiliza la búsqueda para responsable, usuario afectado, módulo o contenido.","Filtra por acción: crear, modificar, activar, desactivar o eliminar.","Selecciona Desde y Hasta para limitar el periodo.","Presiona el icono del ojo en la operación.","Revisa fecha, responsable, módulo, acción, persona afectada y motivo.","Consulta ¿Qué cambió? para comparar valores o leer el detalle completo."],"Se obtiene una explicación legible y trazable de la operación.","La Auditoría es global y no modifica información; sirve para control y seguimiento."),
 guia("configuracion","bi-gear","Configuración","Menú → Configuración","Personalizar la presentación y consultar el estado técnico.",["Sesión iniciada"],["Selecciona un color principal.","Elige densidad Compacta o Cómoda.","Selecciona la vista que se abrirá al iniciar sesión.","Presiona Guardar apariencia.","Utiliza Restaurar para volver a los valores recomendados.","En Información del sistema revisa empresa, usuario, conexión, versión y dispositivo.","Presiona Copiar información cuando solicites soporte."],"La preferencia visual queda guardada en el dispositivo sin cambiar reglas laborales.","Cada dispositivo puede conservar una apariencia diferente."),
 guia("movil","bi-phone","Uso desde celular","Abrir la dirección del sistema en el navegador móvil","Trabajar cómodamente desde una pantalla pequeña.",["Navegador actualizado","Conexión a Internet"],["Usa la barra inferior fija para cambiar de módulo.","Mantén presionado un icono para ver el nombre de la vista.","Desplaza horizontalmente pestañas o tablas cuando sea necesario.","Dentro de un modal desplaza solo el contenido; los botones permanecen accesibles.","Cierra el modal antes de cambiar de módulo.","Si no aparece una actualización, cierra completamente la pestaña y vuelve a abrirla."],"La aplicación mantiene navegación y formularios adaptados al teléfono.","No utilices el zoom del navegador mientras completas formularios."),
 guia("ayuda","bi-life-preserver","Problemas frecuentes","Manual → Problemas frecuentes","Resolver verificaciones básicas antes de solicitar soporte.",["Acceso al sistema"],["Si no carga una vista, comprueba Internet y vuelve a abrirla.","Si un colaborador no aparece, revisa estado activo y filtros.","Si no calcula asistencia, verifica horario, fecha y marcaciones.","Si un selector está vacío, completa primero su registro padre: sucursal, área o subárea.","Si falla una importación, revisa documento y formato de fecha/hora.","Si un cambio no aparece, confirma en Auditoría si fue guardado.","Copia Información del sistema y envíala al soporte técnico."],"El usuario identifica la causa o entrega información suficiente para recibir soporte.","No elimines registros para intentar solucionar un problema de visualización.")
];

function guia(id,icono,titulo,ruta,objetivo,requisitos,pasos,resultado,consejo){return{id,icono,titulo,ruta,objetivo,texto:objetivo,requisitos,pasos,resultado,consejo};}

let modal;
export function iniciarManual(){
 if(document.getElementById("modalManualSistema"))return;
 modal=document.createElement("div");modal.id="modalManualSistema";modal.className="modal-manual-sistema";modal.hidden=true;modal.setAttribute("aria-hidden","true");
 modal.innerHTML=`<article><header><div><span>CENTRO DE AYUDA</span><h2>Manual del sistema</h2><p>Guía completa de Control de Asistencia</p></div><button type="button" id="cerrarManualSistema" aria-label="Cerrar"><i class="bi bi-x-lg"></i></button></header><div class="manual-herramientas"><i class="bi bi-search"></i><input id="buscarManualSistema" type="search" placeholder="Buscar una función, botón o módulo…"></div><div class="manual-layout"><nav>${SECCIONES_MANUAL.map((s,i)=>`<button type="button" data-manual="${s.id}" class="${i===0?"activo":""}"><i class="bi ${s.icono}"></i><span>${s.titulo}</span></button>`).join("")}</nav><main id="contenidoManualSistema"></main></div></article>`;
 document.body.appendChild(modal);
 modal.querySelector("#cerrarManualSistema").addEventListener("click",cerrarManual);
 modal.addEventListener("click",e=>{if(e.target===modal)cerrarManual();const b=e.target.closest("[data-manual]");if(b)mostrarSeccion(b.dataset.manual);});
 modal.querySelector("#buscarManualSistema").addEventListener("input",e=>buscarManual(e.target.value));
 mostrarSeccion("inicio");
}
export function abrirManual(){if(!modal)iniciarManual();modal.hidden=false;modal.setAttribute("aria-hidden","false");document.body.classList.add("manual-abierto");setTimeout(()=>modal.querySelector("#buscarManualSistema")?.focus(),30);}
function cerrarManual(){modal.hidden=true;modal.setAttribute("aria-hidden","true");document.body.classList.remove("manual-abierto");}
function mostrarSeccion(id){const s=SECCIONES_MANUAL.find(x=>x.id===id)||SECCIONES_MANUAL[0];modal.querySelectorAll("[data-manual]").forEach(b=>b.classList.toggle("activo",b.dataset.manual===s.id));modal.querySelector("#contenidoManualSistema").innerHTML=`<section class="manual-seccion"><div class="manual-icono"><i class="bi ${s.icono}"></i></div><span>MANUAL PASO A PASO</span><h3>${s.titulo}</h3><div class="manual-ruta"><i class="bi bi-signpost-split"></i><div><small>RUTA PARA LLEGAR</small><strong>${s.ruta}</strong></div></div><p>${s.objetivo}</p><div class="manual-vista-guiada"><div class="manual-captura-barra"><i class="bi ${s.icono}"></i><strong>${s.titulo}</strong><span>Vista guiada</span></div><div class="manual-captura-cuerpo"><aside>${s.pasos.slice(0,4).map((p,i)=>`<b>${i+1}</b>`).join("")}</aside><div><span class="manual-captura-etiqueta">${s.ruta.split("→").pop().trim()}</span><h4>${s.titulo}</h4><p>${s.objetivo}</p><div class="manual-captura-campos"><i></i><i></i><i></i></div><button type="button" tabindex="-1">Acción principal</button></div></div><footer>Los números corresponden a los primeros pasos indicados debajo.</footer></div><div class="manual-requisitos"><h4><i class="bi bi-clipboard-check"></i> Antes de empezar</h4><ul>${s.requisitos.map(r=>`<li>${r}</li>`).join("")}</ul></div><h4 class="manual-titulo-pasos">Procedimiento detallado</h4><ol>${s.pasos.map(p=>`<li>${p}</li>`).join("")}</ol><div class="manual-resultado"><i class="bi bi-check-circle"></i><div><strong>Resultado esperado</strong><p>${s.resultado}</p></div></div><div class="manual-consejo"><i class="bi bi-lightbulb"></i><div><strong>Recomendación</strong><p>${s.consejo}</p></div></div></section>`;}
function buscarManual(valor){const q=String(valor||"").trim().toLocaleLowerCase("es");if(!q){mostrarSeccion("inicio");return;}const encontrados=SECCIONES_MANUAL.filter(s=>`${s.titulo} ${s.texto} ${s.pasos.join(" ")}`.toLocaleLowerCase("es").includes(q));modal.querySelectorAll("[data-manual]").forEach(b=>b.classList.remove("activo"));modal.querySelector("#contenidoManualSistema").innerHTML=encontrados.length?`<div class="manual-resultados"><h3>Resultados (${encontrados.length})</h3>${encontrados.map(s=>`<button type="button" data-manual="${s.id}"><i class="bi ${s.icono}"></i><div><strong>${s.titulo}</strong><span>${s.texto}</span></div></button>`).join("")}</div>`:`<div class="manual-sin-resultados"><i class="bi bi-search"></i><h3>Sin resultados</h3><p>Prueba con asistencia, horarios, empleados, auditoría o marcación.</p></div>`;}
