const SECCIONES_MANUAL=[
 guia("inicio","bi-house","Primeros pasos","Inicio de sesión → Dashboard","Conocer la navegación y preparar el sistema antes de registrar asistencia.",["Cuenta de usuario activa","Empresa registrada"],["Ingresa con tu correo y contraseña.","En computadora utiliza el menú lateral; en celular utiliza la barra inferior fija.","Presiona tu avatar para editar nombre, correo o contraseña.","Abre Manual cuando necesites consultar un procedimiento.","Completa primero Compañía y después registra a los colaboradores."],"El usuario queda dentro del Dashboard y puede navegar según sus permisos.","El orden recomendado es: Compañía → estructura organizacional → colaboradores → horarios → asistencia."),
 guia("dashboard","bi-speedometer2","Dashboard","Menú → Dashboard","Revisar rápidamente el estado diario y el acumulado mensual.",["Colaboradores activos","Horarios asignados"],["Selecciona la fecha de consulta y presiona Actualizar.","Si corresponde, filtra por sucursal, área o subárea.","Presiona una tarjeta superior para ver las personas incluidas en el indicador.","Revisa Alertas del día para identificar ausencias o marcaciones incompletas.","En Configuración pendiente abre Sin horario o Sin ubicación para corregir al personal.","Usa los accesos rápidos para continuar con la gestión necesaria."],"El Dashboard muestra cifras y listas correspondientes a la fecha y filtros elegidos.","Las tarjetas son accesos de consulta; las modificaciones se realizan desde el módulo correspondiente."),
 guia("empresa","bi-building","Datos de la compañía","Compañía → Información","Registrar los datos generales utilizados en pantallas y reportes.",["RUC y razón social","Dirección y datos de contacto"],["Abre Compañía y permanece en Información.","Completa RUC, razón social y giro de negocio.","Registra dirección, departamento, provincia y distrito.","Completa teléfono, correo y demás información disponible.","Revisa los datos y presiona Guardar cambios.","Si administras representantes, agrégalos desde la sección correspondiente."],"La información queda disponible para reportes y datos institucionales.","Evita abreviaturas diferentes a las registradas legalmente en la razón social."),
 guia("sucursales","bi-buildings","Sucursales","Compañía → Sucursales","Crear los centros de trabajo de la empresa.",["Datos de la compañía guardados","Nombre y dirección de la sede"],["Abre la pestaña Sucursales.","Presiona Nueva sucursal.","Ingresa un nombre claro, por ejemplo: Sede Central o Sucursal Mala.","Completa dirección y datos adicionales solicitados.","Verifica el estado inicial y presiona Guardar.","Usa editar para actualizar una sede existente; desactívala si ya no debe utilizarse."],"La sucursal aparece disponible al crear áreas y asignar colaboradores.","No crees dos sucursales para la misma sede; primero utiliza la búsqueda."),
 guia("areas","bi-diagram-3","Áreas","Compañía → Áreas","Organizar las unidades principales de trabajo.",["Al menos una sucursal creada","Nombre oficial del área"],["Abre la pestaña Áreas.","Presiona Nueva área.","Escribe el nombre, por ejemplo Administración, Ventas o Docencia.","Selecciona la sucursal cuando el formulario lo solicite.","Agrega una descripción breve si está disponible.","Presiona Guardar y confirma que aparezca en el listado."],"El área queda disponible para subáreas y colaboradores.","Utiliza nombres uniformes; evita crear Administración y Área Administrativa como registros distintos si representan lo mismo."),
 guia("subareas","bi-bezier2","Subáreas","Compañía → Subáreas","Crear divisiones internas dependientes de un área.",["Sucursal creada","Área creada"],["Abre la pestaña Subáreas.","Presiona Nueva subárea.","Selecciona primero la sucursal.","Selecciona el área a la que pertenecerá.","Escribe el nombre de la subárea.","Guarda y revisa la relación mostrada en el listado."],"La estructura Sucursal → Área → Subárea queda disponible para asignar personal.","Si el selector de área está vacío, revisa primero que la sucursal tenga áreas registradas."),
 guia("colaboradores","bi-person-plus","Colaboradores","Empleados → Colaboradores","Registrar y mantener la ficha completa del personal.",["Sucursal, área y subárea creadas","Documento y datos del colaborador"],["Abre Empleados y selecciona Colaboradores.","Presiona Nuevo colaborador.","En Información general completa apellidos, nombres, documento, fecha de nacimiento, género y contacto.","En Organización selecciona sucursal, área y subárea.","En Información adicional registra cargo, profesión y fechas de contrato.","Revisa los campos obligatorios y presiona Guardar.","Utiliza buscar, editar, activar, desactivar o eliminar según corresponda."],"El colaborador aparece activo y disponible para asignación de horarios y permisos.","Busca primero por apellidos o documento para evitar duplicados."),
 guia("crear-horario","bi-clock","Crear un horario","Empleados → Horarios → Nuevo horario","Definir una jornada reutilizable antes de asignarla.",["Horas de entrada y salida definidas","Regla de refrigerio conocida"],["Abre Horarios y presiona Nuevo horario.","Asigna un nombre reconocible, por ejemplo Horario administrativo.","Registra entrada y salida programadas.","Configura refrigerio cuando corresponda.","Completa tolerancias y reglas propias del horario únicamente en esta vista.","Revisa si cruza medianoche y las ventanas permitidas.","Presiona Guardar horario."],"El horario aparece en el listado y puede asignarse a uno o varios días.","No repitas estas reglas en Configuración; cada jornada conserva sus propios criterios."),
 guia("asignar-horario","bi-calendar-check","Asignar horarios","Empleados → Horarios → Seleccionar horario → Asignar","Programar cuándo se aplicará una jornada a un colaborador.",["Colaborador activo","Horario creado"],["Busca y selecciona el horario que deseas aplicar.","Presiona Asignar y selecciona al colaborador por apellidos y nombres.","Elige Diaria para una fecha específica, Semanal para patrones por día o Mensual para el calendario.","En Semanal agrega horarios a los días correspondientes y configura las semanas del patrón.","Indica Desde y Hasta para repetir el patrón durante el periodo.","En Mensual marca directamente los días del calendario.","Revisa el resumen final y confirma la asignación."],"El colaborador queda programado y el cambio aparece en Auditoría.","Si el periodo termina a mitad de mes, el sistema aplica el patrón solo hasta la fecha final."),
 guia("permisos","bi-file-earmark-check","Permisos","Empleados → Permisos","Registrar una autorización o ausencia justificada del colaborador.",["Colaborador registrado","Fechas, motivo y sustento disponibles"],["Abre Permisos y busca al colaborador.","Selecciona al colaborador y presiona Nuevo permiso.","Elige el tipo de permiso.","Indica fecha de inicio y término; si es por horas, registra hora inicial y final.","Escribe el motivo obligatorio y observaciones necesarias.","Adjunta PDF, JPG o PNG cuando exista sustento.","Selecciona el estado inicial y presiona Guardar permiso."],"El permiso aparece en el calendario y se considera en la evaluación de asistencia.","Verifica cuidadosamente fechas y horas antes de aprobar un permiso."),
 guia("feriados","bi-calendar2-event","Feriados","Empleados → Feriados","Registrar días especiales y definir su tratamiento laboral.",["Fecha oficial confirmada","Criterio laboral definido"],["Abre Feriados y presiona Nuevo feriado.","Ingresa nombre y tipo de fecha especial.","Selecciona fecha de inicio y término.","Activa Descanso remunerado cuando corresponda.","Define si las horas son compensables y si se permitirán marcaciones.","Agrega una descripción u observación.","Guarda y comprueba el evento en el calendario."],"La fecha queda identificada en los cálculos y calendarios del personal.","La configuración debe corresponder a la política de la empresa y a la norma aplicable."),
 guia("diario","bi-calendar-day","Resumen diario","Asistencia → Resumen diario","Consultar el estado individual de asistencia de una fecha.",["Horarios asignados","Marcaciones registradas o importadas"],["Selecciona la fecha con las flechas, el calendario o el botón Hoy.","Busca al colaborador o filtra por ubicación y estado.","Revisa entrada, refrigerio, salida, horas trabajadas, jornada y horas extra.","Presiona Ver para abrir el detalle diario.","Usa Recalcular después de corregir o importar información.","Presiona Registrar marcación para elegir colaborador y tipo de registro."],"El resumen refleja el estado calculado de cada colaborador para el día.","Una marcación incompleta debe revisarse antes del cierre del periodo."),
 guia("marcaciones","bi-fingerprint","Marcaciones e importación","Asistencia → Resumen diario o Marcaciones","Registrar manualmente o importar eventos del reloj.",["Documento del colaborador válido","Fecha y hora correctas"],["Para registro manual presiona Registrar marcación.","Selecciona colaborador y tipo: entrada, inicio/fin de refrigerio o salida.","Presiona Continuar, ingresa la hora real y escribe el motivo.","Confirma con Registrar marcación.","Para carga masiva presiona Importar y selecciona Excel o CSV.","Verifica las columnas de documento y fecha/hora en la vista previa.","Confirma únicamente las filas válidas y revisa luego el historial."],"Las marcaciones se incorporan al cálculo diario y quedan auditadas.","No importes dos veces el mismo archivo sin revisar posibles duplicados."),
 guia("mensual","bi-calendar3","Resumen mensual y reportes","Asistencia → Resumen mensual","Analizar un periodo y generar reportes.",["Periodo con información procesada","Filtros organizacionales definidos"],["Selecciona Desde y Hasta según el periodo de corte.","Aplica filtros de colaborador, sucursal, área o subárea.","Revisa días programados, asistencias, tardanzas, ausencias y permisos.","Comprueba horas asignadas, trabajadas, ausentes y extras.","Presiona Ver detalle para consultar los días de un colaborador.","Utiliza Descargar, elige tipo de reporte y formato.","Revisa la vista previa antes de generar Excel o PDF."],"Se obtiene un reporte del periodo con los datos institucionales y filtros aplicados.","La exportación se realiza aquí; no es necesario exportar desde el resumen diario."),
 guia("auditoria","bi-share","Auditoría global","Menú → Auditoría","Consultar quién realizó cada cambio y qué información fue afectada.",["Operaciones registradas en el sistema"],["Utiliza la búsqueda para responsable, usuario afectado, módulo o contenido.","Filtra por acción: crear, modificar, activar, desactivar o eliminar.","Selecciona Desde y Hasta para limitar el periodo.","Presiona el icono del ojo en la operación.","Revisa fecha, responsable, módulo, acción, persona afectada y motivo.","Consulta ¿Qué cambió? para comparar valores o leer el detalle completo."],"Se obtiene una explicación legible y trazable de la operación.","La Auditoría es global y no modifica información; sirve para control y seguimiento."),
 guia("configuracion","bi-gear","Configuración","Menú → Configuración","Personalizar la presentación y consultar el estado técnico.",["Sesión iniciada"],["Selecciona un color principal.","Elige densidad Compacta o Cómoda.","Selecciona la vista que se abrirá al iniciar sesión.","Presiona Guardar apariencia.","Utiliza Restaurar para volver a los valores recomendados.","En Información del sistema revisa empresa, usuario, conexión, versión y dispositivo.","Presiona Copiar información cuando solicites soporte."],"La preferencia visual queda guardada en el dispositivo sin cambiar reglas laborales.","Cada dispositivo puede conservar una apariencia diferente."),
 guia("regularizaciones","bi-pencil-square","Regularizaciones","Asistencia → Regularizaciones","Solicitar, aprobar o rechazar una corrección de marcación con trazabilidad.",["Colaborador activo","Fecha, hora y motivo de la corrección"],["Presiona Nueva solicitud.","Selecciona al colaborador.","Indica fecha, tipo de marcación, hora original y hora solicitada.","Escribe un motivo claro y registra la solicitud.","Un responsable revisa la bandeja y presiona Aprobar o Rechazar.","Al aprobar, el sistema registra la marcación corregida sin borrar el antecedente.","Consulta Auditoría para revisar responsable y decisión."],"La solicitud queda pendiente, aprobada o rechazada y conserva su historial.","No apruebes una regularización sin verificar el sustento y la hora real."),
 guia("cierres","bi-lock","Cierres de asistencia","Asistencia → Cierres","Proteger periodos revisados e impedir cambios administrativos posteriores.",["Periodo procesado","Sin regularizaciones, permisos ni horas extra pendientes"],["Selecciona las fechas Desde y Hasta.","Presiona Verificar periodo.","Revisa la cantidad de pendientes indicada por el sistema.","Resuelve los pendientes si el periodo aparece bloqueado.","Cuando esté listo, escribe la observación del cierre.","Presiona Cerrar periodo.","Para reabrir, un administrador debe indicar un motivo obligatorio."],"El periodo queda cerrado o reabierto con responsable, fecha y observación.","Cierra únicamente después de revisar el resumen mensual y sus detalles."),
 guia("movil","bi-phone","Uso desde celular","Abrir la dirección del sistema en el navegador móvil","Trabajar cómodamente desde una pantalla pequeña.",["Navegador actualizado","Conexión a Internet"],["Usa la barra inferior fija para cambiar de módulo.","Mantén presionado un icono para ver el nombre de la vista.","Desplaza horizontalmente pestañas o tablas cuando sea necesario.","Dentro de un modal desplaza solo el contenido; los botones permanecen accesibles.","Cierra el modal antes de cambiar de módulo.","Si no aparece una actualización, cierra completamente la pestaña y vuelve a abrirla."],"La aplicación mantiene navegación y formularios adaptados al teléfono.","No utilices el zoom del navegador mientras completas formularios."),
 guia("ayuda","bi-life-preserver","Problemas frecuentes","Manual → Problemas frecuentes","Resolver verificaciones básicas antes de solicitar soporte.",["Acceso al sistema"],["Si no carga una vista, comprueba Internet y vuelve a abrirla.","Si un colaborador no aparece, revisa estado activo y filtros.","Si no calcula asistencia, verifica horario, fecha y marcaciones.","Si un selector está vacío, completa primero su registro padre: sucursal, área o subárea.","Si falla una importación, revisa documento y formato de fecha/hora.","Si un cambio no aparece, confirma en Auditoría si fue guardado.","Copia Información del sistema y envíala al soporte técnico."],"El usuario identifica la causa o entrega información suficiente para recibir soporte.","No elimines registros para intentar solucionar un problema de visualización.")
];

SECCIONES_MANUAL.push(
 guia("incidencias","bi-exclamation-triangle","Incidencias de asistencia","Asistencia → Incidencias","Detectar jornadas que requieren revisión antes de considerarlas definitivas.",["Marcaciones y horarios procesados"],["Selecciona el periodo o fecha disponible.","Revisa registros incompletos, tardanzas, ausencias y datos inconsistentes.","Abre el detalle del colaborador.","Comprueba horario, permisos y marcaciones.","Realiza la corrección desde la función correspondiente y vuelve a calcular."],"La incidencia queda aclarada mediante una corrección trazable.","Una incidencia es una alerta; no significa automáticamente una falta sancionable."),
 guia("movil-admin","bi-phone-vibrate","Administración de marcación móvil","Empleados → Marcación móvil","Habilitar, autorizar y controlar los celulares desde los que puede marcar cada colaborador.",["Colaborador activo","Correo móvil único"],["Busca al colaborador.","Habilita su acceso móvil y confirma el correo.","El colaborador crea su contraseña desde el enlace móvil.","Cuando solicite autorización, revisa el dispositivo y apruébalo.","Usa Revocar cuando el equipo se pierda o cambie de propietario.","Consulta su historial para verificar ubicaciones y validaciones."],"El colaborador puede marcar únicamente desde un dispositivo autorizado.","No autorices un equipo si el modelo o la persona solicitante no coinciden."),
 guia("movil-marcacion","bi-geo-alt","Marcación del colaborador desde celular","Enlace móvil → Marcación móvil","Registrar entrada, refrigerio y salida con ubicación, validación del dispositivo y evidencia opcional.",["Celular autorizado","GPS y conexión activos"],["Ingresa desde el celular autorizado.","Espera a que la tarjeta del GPS cambie a verde.","Presiona el tipo de marcación disponible.","Agrega comentario o fotografía si deseas dejar evidencia.","Continúa y valida tu identidad con huella, rostro o seguridad local.","Confirma el registro y comparte el comprobante PDF si lo necesitas."],"La marcación queda guardada con hora del servidor, GPS, dirección, validación y evidencia opcional.","No marques hasta que el GPS indique ubicación obtenida."),
 guia("cc-alertas","bi-bell","Centro de alertas","Centro de control → Alertas","Reunir avisos importantes de asistencia, permisos, móviles y suscripción.",["Información actualizada"],["Abre Centro de control.","Selecciona Alertas.","Filtra por categoría si existen muchos avisos.","Abre el aviso o dirígete al módulo indicado.","Corrige la causa y presiona Actualizar."],"Las situaciones que requieren atención quedan identificadas desde un solo lugar.","Atiende primero las alertas que impidan calcular o cerrar asistencia."),
 guia("cc-pendientes","bi-inboxes","Bandeja de pendientes","Centro de control → Pendientes","Revisar en una sola bandeja permisos, regularizaciones, horas extra y solicitudes móviles.",["Solicitudes registradas"],["Selecciona Pendientes.","Filtra por el tipo de solicitud.","Revisa colaborador, fecha, detalle y estado.","Abre la acción disponible.","Aprueba o rechaza después de validar el sustento."],"Cada solicitud queda resuelta desde su flujo correspondiente.","No decidas únicamente por el título; revisa fecha, motivo y evidencia."),
 guia("cc-analitica","bi-graph-up-arrow","Analítica y reincidencias","Centro de control → Analítica","Comparar meses y detectar tendencias de tardanza, ausencia e incidencias.",["Al menos dos meses con datos"],["Selecciona el mes de análisis.","Presiona Calcular.","Compara el mes elegido con el anterior.","Revisa gráficos e indicadores.","Consulta el ranking de reincidencias como información preventiva."],"Se obtiene una lectura comparativa para tomar decisiones de gestión.","El ranking es informativo y no aplica sanciones automáticamente."),
 guia("cc-calendario","bi-calendar3","Calendario operativo","Centro de control → Calendario","Visualizar en calendario feriados, permisos y eventos relevantes de asistencia.",["Fechas especiales o permisos registrados"],["Selecciona Calendario.","Navega con las flechas entre meses.","Presiona Hoy para regresar al mes actual.","Revisa los eventos mostrados en cada fecha.","Abre el módulo correspondiente si necesitas modificarlos."],"La planificación mensual se consulta de manera visual.","Modifica el registro original; el calendario funciona principalmente como consulta."),
 guia("cc-planillas","bi-file-earmark-spreadsheet","Planillas y cierre diario","Centro de control → Planillas","Exportar información para remuneraciones y revisar automáticamente las jornadas del día.",["Periodo procesado","Colaboradores y marcaciones revisados"],["Selecciona Desde y Hasta.","Elige una plantilla o usa el formato estándar.","Descarga el Excel de planillas.","Revisa el estado del cierre diario.","Presiona Revisar cierre ahora cuando quieras ejecutar la comprobación manual."],"Se genera un archivo con días trabajados, faltas, tardanzas, permisos y horas extra.","La exportación es un apoyo; valida los totales antes de procesar remuneraciones."),
 guia("cc-mapa","bi-map","Mapa y geocercas","Centro de control → Mapa","Consultar sucursales, marcaciones y registros fuera de las zonas configuradas.",["Sucursales con coordenadas","Marcaciones móviles"],["Selecciona Mapa.","Elige Todo, Sucursales o Fuera de zona.","Ubica los puntos en el mapa.","Selecciona una sucursal para revisar su configuración.","Contrasta ubicación, dirección y precisión de la marcación."],"Se identifica visualmente dónde se realizaron las marcaciones.","Una precisión GPS muy amplia debe revisarse antes de concluir que hubo una marcación fuera de zona."),
 guia("cc-anuncios","bi-megaphone","Anuncios internos","Centro de control → Anuncios","Publicar comunicaciones para administradores, colaboradores móviles o ambos.",["Título, mensaje y fecha final"],["Selecciona Anuncios.","Escribe un título breve.","Redacta el mensaje.","Define quiénes podrán verlo.","Indica hasta cuándo estará visible.","Publica y comprueba el anuncio en el historial."],"El comunicado aparece al público seleccionado durante su vigencia.","No publiques información confidencial que no deba mostrarse en celulares."),
 guia("cc-plantillas","bi-layout-text-window","Plantillas de planilla","Centro de control → Plantillas","Guardar diseños reutilizables para exportar Excel de remuneraciones.",["Columnas requeridas definidas"],["Escribe el nombre de la plantilla.","Define encabezado y color principal.","Marca las columnas necesarias.","Guarda la plantilla.","Revisa la vista previa.","Selecciona Usar y descargar desde Planillas."],"La plantilla queda disponible para futuras exportaciones con datos reales.","La plantilla guarda el formato; no representa por sí sola un reporte del periodo."),
 guia("cc-respaldo","bi-shield-check","Respaldo y restauración","Centro de control → Respaldo","Descargar una copia JSON de los registros de la empresa o restaurar una copia válida.",["Permisos administrativos","Archivo de respaldo válido para restaurar"],["Para respaldar, presiona Crear y descargar respaldo.","Guarda el JSON en un lugar seguro.","Para restaurar, selecciona un respaldo generado por el sistema.","Valida el archivo.","Revisa la advertencia y confirma únicamente si corresponde.","Consulta la bitácora de operaciones críticas."],"La empresa conserva una copia exportable o recupera documentos respaldados.","La restauración es una operación crítica; no utilices archivos editados manualmente."),
 guia("asistente","bi-stars","Asistente interno","Botón flotante del asistente","Consultar datos y ejecutar accesos rápidos mediante preguntas escritas.",["Sesión iniciada","Datos cargados en el sistema"],["Abre el asistente desde el botón flotante.","Escribe una pregunta concreta, por ejemplo: quiénes llegaron tarde hoy.","Revisa la respuesta y el periodo interpretado.","Utiliza los botones ofrecidos para abrir vistas o descargar reportes.","Comprueba los resultados en el módulo original cuando tomarás una decisión."],"El asistente resume información existente y facilita accesos frecuentes.","El asistente no reemplaza la revisión del reporte ni crea datos que no estén registrados.")
);

const AMPLIACIONES_MANUAL={
 inicio:{categoria:"Inicio",funciones:["Ingresar y cerrar sesión","Usar menú lateral o navegación móvil","Cambiar tamaño de toda la interfaz","Administrar la cuenta personal"],ejemplo:{situacion:"Es la primera vez que una empresa utilizará el sistema.",pasos:["Registrar la compañía y su estructura.","Crear colaboradores y horarios.","Asignar horarios antes de revisar asistencia."],resultado:"La empresa queda preparada para comenzar a registrar marcaciones."}},
 dashboard:{categoria:"Inicio",funciones:["Consultar indicadores diarios","Abrir listas desde las tarjetas","Detectar configuración pendiente","Revisar actividad reciente"],ejemplo:{situacion:"El administrador inicia la jornada y quiere saber quiénes llegaron tarde.",pasos:["Selecciona la fecha de hoy.","Presiona la tarjeta Tardanzas.","Revisa los colaboradores incluidos y abre Asistencia."],resultado:"Obtiene la lista que necesita revisar sin buscar persona por persona."}},
 empresa:{categoria:"Compañía",funciones:["Guardar datos legales","Completar dirección y contacto","Preparar encabezados de reportes"],ejemplo:{situacion:"La empresa debe emitir reportes con su RUC y razón social correctos.",pasos:["Registra RUC y razón social.","Completa ubicación y contacto.","Guarda y genera una vista previa de reporte."],resultado:"Los datos institucionales aparecen correctamente en los documentos."}},
 sucursales:{categoria:"Compañía",funciones:["Crear sedes","Guardar dirección","Activar o desactivar","Relacionar empleados y geocercas"],ejemplo:{situacion:"La empresa abre una nueva sede en San Isidro.",pasos:["Crea Sucursal San Isidro.","Registra su dirección.","Asigna áreas y colaboradores."],resultado:"La nueva sede puede filtrarse en asistencia y reportes."}},
 areas:{categoria:"Compañía",funciones:["Organizar departamentos","Relacionar áreas con sucursales","Filtrar personal y reportes"],ejemplo:{situacion:"La sede central necesita separar Recursos Humanos de Contabilidad.",pasos:["Crea ambas áreas.","Asócialas a la sede central.","Asigna cada colaborador a su área."],resultado:"Los reportes pueden agruparse y filtrarse correctamente."}},
 subareas:{categoria:"Compañía",funciones:["Crear divisiones internas","Relacionar subárea con área","Afinar filtros organizacionales"],ejemplo:{situacion:"Recursos Humanos tiene Reclutamiento y Selección.",pasos:["Selecciona la sucursal.","Elige Recursos Humanos.","Crea Reclutamiento y Selección."],resultado:"El personal queda clasificado con mayor precisión."}},
 colaboradores:{categoria:"Empleados",funciones:["Crear ficha personal","Asignar ubicación organizacional","Activar o desactivar","Editar y consultar horario"],ejemplo:{situacion:"Ingresa un nuevo trabajador llamado Juan Carlos.",pasos:["Registra documento, apellidos y nombres.","Selecciona sucursal, área y subárea.","Guarda y luego asígnale un horario."],resultado:"Juan queda disponible para permisos, asistencia y marcación móvil."}},
 "crear-horario":{categoria:"Empleados",funciones:["Definir entrada y salida","Configurar refrigerio","Establecer tolerancias","Controlar ventanas de marcación"],ejemplo:{situacion:"Administración trabaja de 08:30 a 17:30 con almuerzo de 13:00 a 14:00.",pasos:["Crea Horario administrativo.","Registra la jornada y refrigerio.","Configura la tolerancia permitida."],resultado:"La plantilla horaria puede reutilizarse con varios colaboradores."}},
 "asignar-horario":{categoria:"Empleados",funciones:["Asignación diaria","Patrón semanal","Calendario mensual","Reemplazo de días sin horario"],ejemplo:{situacion:"Oscar trabaja de lunes a viernes y descansa sábado y domingo.",pasos:["Selecciona asignación semanal.","Asigna el horario de lunes a viernes.","Deja sábado y domingo sin horario y confirma el periodo."],resultado:"Los fines de semana quedan como descanso y no generan ausencias."}},
 permisos:{categoria:"Empleados",funciones:["Registrar permisos completos o por horas","Adjuntar sustento","Aprobar o rechazar","Justificar tiempo autorizado"],ejemplo:{situacion:"Una colaboradora tiene cita médica de 10:00 a 12:00.",pasos:["Crea un permiso por horas.","Registra el intervalo y motivo.","Adjunta el sustento y aprueba."],resultado:"Solo ese intervalo se considera justificado en su asistencia."}},
 feriados:{categoria:"Empleados",funciones:["Registrar feriados","Definir descanso remunerado","Permitir marcaciones","Configurar compensación"],ejemplo:{situacion:"El 30 de agosto es feriado y la empresa no trabajará.",pasos:["Crea el feriado.","Activa descanso remunerado.","No permitas marcaciones si corresponde."],resultado:"El día no se calcula como ausencia ordinaria."}},
 diario:{categoria:"Asistencia",funciones:["Consultar estado diario","Abrir detalle por persona","Agregar marcaciones","Recalcular jornada"],ejemplo:{situacion:"Oscar marcó entrada y salida, pero olvidó terminar el refrigerio.",pasos:["Busca a Oscar en la fecha.","Abre Ver detalle.","Registra o regulariza la marcación faltante y recalcula."],resultado:"La jornada deja de aparecer incompleta."}},
 marcaciones:{categoria:"Asistencia",funciones:["Consultar cada evento","Ver mapa y dirección","Registrar manualmente","Importar Excel o CSV"],ejemplo:{situacion:"El reloj biométrico entrega un Excel con todas las horas del día.",pasos:["Abre Importar.","Selecciona el archivo.","Valida documentos y fechas antes de confirmar."],resultado:"Las filas válidas se incorporan sin registrar manualmente una por una."}},
 mensual:{categoria:"Asistencia",funciones:["Analizar rangos","Comparar horas","Ver detalle diario","Exportar Excel y PDF"],ejemplo:{situacion:"Recursos Humanos necesita el resumen de agosto para planilla.",pasos:["Selecciona del 01 al 31 de agosto.","Filtra la sede necesaria.","Revisa ausencias y extras, luego descarga el reporte."],resultado:"Obtiene el consolidado del periodo con sus datos institucionales."}},
 incidencias:{categoria:"Asistencia",funciones:["Detectar registros incompletos","Identificar inconsistencias","Derivar a corrección","Evitar cierres con errores"],ejemplo:{situacion:"Juan tiene entrada a las 08:30, pero no registra salida.",pasos:["Abre la incidencia.","Confirma si olvidó marcar.","Registra la salida con motivo o genera una regularización."],resultado:"La jornada puede recalcularse con información sustentada."}},
 regularizaciones:{categoria:"Asistencia",funciones:["Solicitar corrección","Aprobar o rechazar","Conservar antecedente","Registrar responsable y motivo"],ejemplo:{situacion:"Una entrada quedó registrada a las 10:15 por un problema del celular, pero correspondía a las 08:30.",pasos:["Solicita cambiar Entrada de 10:15 a 08:30.","Explica el problema y adjunta la referencia disponible.","El responsable revisa y aprueba."],resultado:"Se agrega la marcación corregida sin borrar silenciosamente el antecedente."},advertencia:"Una regularización debe sustentarse; no se utiliza para alterar horas sin revisión."},
 cierres:{categoria:"Asistencia",funciones:["Verificar pendientes","Cerrar periodos","Bloquear operaciones administrativas","Reabrir con motivo"],ejemplo:{situacion:"Agosto ya fue revisado y será enviado a planilla.",pasos:["Verifica del 01 al 31 de agosto.","Resuelve permisos, extras y regularizaciones pendientes.","Escribe la observación y cierra."],resultado:"El periodo queda registrado como cerrado y las operaciones protegidas requieren reapertura."},advertencia:"Cierra únicamente cuando el resumen mensual y los pendientes estén revisados."},
 "movil-admin":{categoria:"Empleados",funciones:["Habilitar acceso","Autorizar dispositivo","Revocar equipo","Consultar marcaciones móviles"],ejemplo:{situacion:"Un colaborador cambia de teléfono.",pasos:["Revoca el dispositivo anterior.","El colaborador inicia sesión en el nuevo.","Revisa y autoriza la nueva solicitud."],resultado:"El teléfono antiguo deja de estar autorizado y el nuevo puede marcar."}},
 "movil-marcacion":{categoria:"Marcación móvil",funciones:["Validar GPS","Adjuntar comentario y foto","Validar identidad","Compartir comprobante PDF"],ejemplo:{situacion:"El colaborador llega a una sede y necesita acreditar su entrada.",pasos:["Espera GPS verde.","Presiona Entrada y toma una foto opcional.","Valida la identidad y comparte el comprobante."],resultado:"Conserva un PDF con hora, ubicación, validación y evidencia."}},
 auditoria:{categoria:"Control",funciones:["Buscar operaciones","Filtrar acciones","Comparar cambios","Identificar responsable"],ejemplo:{situacion:"Un horario cambió y el administrador quiere saber quién lo modificó.",pasos:["Busca al colaborador o módulo Horarios.","Abre la operación con el icono del ojo.","Revisa antes, después, responsable y motivo."],resultado:"Se identifica claramente el origen del cambio."}},
 configuracion:{categoria:"Configuración",funciones:["Cambiar color","Elegir densidad","Definir vista inicial","Copiar información técnica"],ejemplo:{situacion:"En una pantalla grande el usuario quiere ver más registros.",pasos:["Elige densidad Compacta.","Selecciona el tamaño global apropiado.","Guarda la apariencia."],resultado:"La interfaz se adapta sin modificar cálculos ni datos."}},
 "cc-alertas":{categoria:"Centro de control",funciones:["Concentrar alertas","Filtrar categorías","Derivar a módulos"],ejemplo:{situacion:"Hay colaboradores sin horario y permisos pendientes.",pasos:["Filtra alertas de Asistencia.","Corrige primero a quienes no tienen horario.","Actualiza la bandeja."],resultado:"Disminuyen las alertas que afectan el cálculo."}},
 "cc-pendientes":{categoria:"Centro de control",funciones:["Unificar solicitudes","Filtrar por tipo","Abrir decisiones"],ejemplo:{situacion:"El responsable debe resolver todo antes del cierre mensual.",pasos:["Filtra cada tipo.","Revisa sustento.","Aprueba o rechaza hasta dejar la bandeja sin pendientes."],resultado:"El periodo queda preparado para verificación y cierre."}},
 "cc-analitica":{categoria:"Centro de control",funciones:["Comparar meses","Graficar indicadores","Mostrar reincidencias"],ejemplo:{situacion:"Las tardanzas parecen haber aumentado en agosto.",pasos:["Calcula agosto.","Compáralo con julio.","Revisa colaboradores recurrentes."],resultado:"La percepción se contrasta con datos medidos."}},
 "cc-calendario":{categoria:"Centro de control",funciones:["Consultar eventos","Navegar por meses","Volver a hoy"],ejemplo:{situacion:"Se desea conocer qué permisos coinciden con un feriado.",pasos:["Abre el mes.","Ubica el feriado.","Revisa eventos cercanos."],resultado:"Se visualiza la planificación sin revisar listas separadas."}},
 "cc-planillas":{categoria:"Centro de control",funciones:["Exportar remuneraciones","Elegir plantilla","Revisar cierre diario"],ejemplo:{situacion:"Contabilidad solicita un Excel con faltas y horas extra.",pasos:["Define el periodo.","Elige la plantilla requerida.","Descarga y valida el Excel."],resultado:"Contabilidad recibe un archivo uniforme con los indicadores seleccionados."}},
 "cc-mapa":{categoria:"Centro de control",funciones:["Ver sedes","Ver marcaciones","Filtrar fuera de zona"],ejemplo:{situacion:"Una marcación figura fuera de la sucursal.",pasos:["Filtra Fuera de zona.","Abre el punto.","Compara distancia y precisión GPS."],resultado:"Se determina si requiere revisión o sustento."}},
 "cc-anuncios":{categoria:"Centro de control",funciones:["Publicar","Segmentar destinatarios","Definir vigencia","Editar historial"],ejemplo:{situacion:"Se comunicará mantenimiento del sistema a usuarios móviles.",pasos:["Escribe el aviso.","Selecciona Solo colaboradores móviles.","Define la fecha final y publica."],resultado:"El anuncio aparece únicamente al público elegido."}},
 "cc-plantillas":{categoria:"Centro de control",funciones:["Elegir columnas","Personalizar encabezado","Guardar formatos"],ejemplo:{situacion:"Una empresa solo requiere DNI, días trabajados y horas extra.",pasos:["Crea la plantilla Planilla básica.","Marca esas columnas.","Guarda y úsala en la exportación."],resultado:"Los siguientes Excel mantienen el mismo formato."}},
 "cc-respaldo":{categoria:"Centro de control",funciones:["Exportar JSON","Validar respaldo","Restaurar","Consultar bitácora"],ejemplo:{situacion:"Antes de una carga masiva se desea conservar una copia.",pasos:["Descarga el respaldo.","Guárdalo con fecha.","Realiza la carga masiva."],resultado:"Existe una copia previa para recuperación controlada."}},
 asistente:{categoria:"Ayuda",funciones:["Responder consultas","Resumir periodos","Abrir módulos","Preparar reportes"],ejemplo:{situacion:"El gerente pregunta quiénes llegaron tarde hoy.",pasos:["Escribe la pregunta.","Revisa nombres y cantidades.","Abre el resumen diario para verificar."],resultado:"Obtiene una respuesta rápida basada en los registros actuales."}},
 movil:{categoria:"Ayuda",funciones:["Navegar en pantallas pequeñas","Usar barra inferior","Desplazar tablas","Operar modales"],ejemplo:{situacion:"El administrador revisa asistencia desde su teléfono.",pasos:["Usa la barra inferior.","Desplaza la tabla horizontalmente.","Mantén visibles las columnas fijas de acciones."],resultado:"Puede consultar y operar sin usar una computadora."}},
 ayuda:{categoria:"Ayuda",funciones:["Diagnóstico básico","Revisión de filtros","Comprobación de datos","Preparación de soporte"],ejemplo:{situacion:"Una marcación no aparece en el resumen.",pasos:["Confirma fecha y filtros.","Busca la marcación en Historial.","Recalcula y copia Información del sistema si persiste."],resultado:"Se resuelve el problema o se entrega información útil a soporte."}}
};

SECCIONES_MANUAL.forEach((seccion)=>Object.assign(seccion,AMPLIACIONES_MANUAL[seccion.id]||{
 categoria:"General",
 funciones:[seccion.objetivo],
 ejemplo:{situacion:`Se necesita utilizar ${seccion.titulo}.`,pasos:seccion.pasos.slice(0,3),resultado:seccion.resultado}
}));

function guia(id,icono,titulo,ruta,objetivo,requisitos,pasos,resultado,consejo){return{id,icono,titulo,ruta,objetivo,texto:objetivo,requisitos,pasos,resultado,consejo};}

let modal;
export function iniciarManual(){
 if(document.getElementById("modalManualSistema"))return;
 modal=document.createElement("div");modal.id="modalManualSistema";modal.className="modal-manual-sistema";modal.hidden=true;modal.setAttribute("aria-hidden","true");
 modal.innerHTML=`<article><header><div><span>CENTRO DE AYUDA</span><h2>Manual del sistema</h2><p>Guía completa de Control de Asistencia</p></div><div class="manual-acciones-cabecera"><button type="button" id="descargarManualPdf"><i class="bi bi-file-earmark-pdf"></i><span>Descargar PDF</span></button><button type="button" id="cerrarManualSistema" aria-label="Cerrar"><i class="bi bi-x-lg"></i></button></div></header><div class="manual-herramientas"><i class="bi bi-search"></i><input id="buscarManualSistema" type="search" placeholder="Buscar una función, botón, ejemplo o módulo…"><span>${SECCIONES_MANUAL.length} guías</span></div><div class="manual-layout"><nav>${SECCIONES_MANUAL.map((s,i)=>`<button type="button" data-manual="${s.id}" class="${i===0?"activo":""}"><i class="bi ${s.icono}"></i><span><small>${s.categoria||"General"}</small>${s.titulo}</span></button>`).join("")}</nav><main id="contenidoManualSistema"></main></div></article>`;
 document.body.appendChild(modal);
 modal.querySelector("#cerrarManualSistema").addEventListener("click",cerrarManual);
 modal.querySelector("#descargarManualPdf").addEventListener("click",descargarManualPdf);
 modal.addEventListener("click",e=>{if(e.target===modal)cerrarManual();const b=e.target.closest("[data-manual]");if(b)mostrarSeccion(b.dataset.manual);});
 modal.querySelector("#buscarManualSistema").addEventListener("input",e=>buscarManual(e.target.value));
 mostrarSeccion("inicio");
}
export function abrirManual(){if(!modal)iniciarManual();modal.hidden=false;modal.setAttribute("aria-hidden","false");document.body.classList.add("manual-abierto");setTimeout(()=>modal.querySelector("#buscarManualSistema")?.focus(),30);}
function cerrarManual(){modal.hidden=true;modal.setAttribute("aria-hidden","true");document.body.classList.remove("manual-abierto");}
function mostrarSeccion(id){const s=SECCIONES_MANUAL.find(x=>x.id===id)||SECCIONES_MANUAL[0];modal.querySelectorAll("[data-manual]").forEach(b=>b.classList.toggle("activo",b.dataset.manual===s.id));modal.querySelector("#contenidoManualSistema").innerHTML=`<section class="manual-seccion"><div class="manual-portada-seccion"><div class="manual-icono"><i class="bi ${s.icono}"></i></div><div><span>${s.categoria||"MANUAL PASO A PASO"}</span><h3>${s.titulo}</h3><p>${s.objetivo}</p></div></div><div class="manual-ruta"><i class="bi bi-signpost-split"></i><div><small>RUTA PARA LLEGAR</small><strong>${s.ruta}</strong></div></div><div class="manual-funciones"><h4><i class="bi bi-grid-1x2"></i> ¿Qué puedes hacer aquí?</h4><div>${s.funciones.map(f=>`<span><i class="bi bi-check2"></i>${f}</span>`).join("")}</div></div><div class="manual-vista-guiada"><div class="manual-captura-barra"><i class="bi ${s.icono}"></i><strong>${s.titulo}</strong><span>Vista guiada</span></div><div class="manual-captura-cuerpo"><aside>${s.pasos.slice(0,4).map((p,i)=>`<b>${i+1}</b>`).join("")}</aside><div><span class="manual-captura-etiqueta">${s.ruta.split("→").pop().trim()}</span><h4>${s.titulo}</h4><p>${s.objetivo}</p><div class="manual-captura-campos"><i></i><i></i><i></i></div><button type="button" tabindex="-1">Acción principal</button></div></div><footer>Los números corresponden a los primeros pasos indicados debajo.</footer></div><div class="manual-requisitos"><h4><i class="bi bi-clipboard-check"></i> Antes de empezar</h4><ul>${s.requisitos.map(r=>`<li>${r}</li>`).join("")}</ul></div><h4 class="manual-titulo-pasos">Procedimiento detallado</h4><ol>${s.pasos.map(p=>`<li>${p}</li>`).join("")}</ol><div class="manual-ejemplo"><header><i class="bi bi-briefcase"></i><div><span>CASO REAL</span><h4>Ejemplo práctico</h4></div></header><p><strong>Situación:</strong> ${s.ejemplo.situacion}</p><ol>${s.ejemplo.pasos.map(p=>`<li>${p}</li>`).join("")}</ol><div><i class="bi bi-arrow-right-circle"></i><p><strong>Resultado del ejemplo:</strong> ${s.ejemplo.resultado}</p></div></div>${s.advertencia?`<div class="manual-advertencia"><i class="bi bi-exclamation-triangle"></i><div><strong>Importante</strong><p>${s.advertencia}</p></div></div>`:""}<div class="manual-resultado"><i class="bi bi-check-circle"></i><div><strong>Resultado esperado</strong><p>${s.resultado}</p></div></div><div class="manual-consejo"><i class="bi bi-lightbulb"></i><div><strong>Recomendación</strong><p>${s.consejo}</p></div></div></section>`;}
function buscarManual(valor){const q=String(valor||"").trim().toLocaleLowerCase("es");if(!q){mostrarSeccion("inicio");return;}const encontrados=SECCIONES_MANUAL.filter(s=>`${s.titulo} ${s.categoria} ${s.texto} ${s.funciones.join(" ")} ${s.pasos.join(" ")} ${s.ejemplo.situacion}`.toLocaleLowerCase("es").includes(q));modal.querySelectorAll("[data-manual]").forEach(b=>b.classList.remove("activo"));modal.querySelector("#contenidoManualSistema").innerHTML=encontrados.length?`<div class="manual-resultados"><h3>Resultados (${encontrados.length})</h3>${encontrados.map(s=>`<button type="button" data-manual="${s.id}"><i class="bi ${s.icono}"></i><div><small>${s.categoria}</small><strong>${s.titulo}</strong><span>${s.texto}</span></div></button>`).join("")}</div>`:`<div class="manual-sin-resultados"><i class="bi bi-search"></i><h3>Sin resultados</h3><p>Prueba con asistencia, horarios, empleados, auditoría, mapa o marcación.</p></div>`;}

async function descargarManualPdf(){
 const boton=modal.querySelector("#descargarManualPdf"),original=boton.innerHTML;
 try{
  const JsPdf=window.jspdf?.jsPDF;if(!JsPdf)throw new Error("El generador PDF todavía no terminó de cargar.");
  boton.disabled=true;boton.innerHTML='<i class="bi bi-arrow-repeat"></i><span>Generando…</span>';
  await new Promise(r=>setTimeout(r,30));
  const logo=await cargarLogoPdf();
  const pdf=new JsPdf({unit:"mm",format:"a4"});let y=0,pagina=1;
  const margen=16,ancho=178;
  const nuevaPagina=()=>{pdf.addPage();pagina++;y=18;encabezadoPdf(pdf,logo);};
  const asegurar=(alto)=>{if(y+alto>280)nuevaPagina();};
  const texto=(valor,tamano=10,color=[51,65,85],negrita=false,sangria=0)=>{pdf.setFont("helvetica",negrita?"bold":"normal");pdf.setFontSize(tamano);pdf.setTextColor(...color);const lineas=pdf.splitTextToSize(String(valor),ancho-sangria);asegurar(lineas.length*(tamano*.42)+3);pdf.text(lineas,margen+sangria,y);y+=lineas.length*(tamano*.42)+3;};
  pdf.setFillColor(30,64,175);pdf.rect(0,0,210,297,"F");pdf.setFillColor(255,255,255);pdf.roundedRect(16,18,178,42,6,6,"F");if(logo)pdf.addImage(logo,"PNG",23,24,30,30);pdf.setTextColor(30,64,175);pdf.setFont("helvetica","bold");pdf.setFontSize(17);pdf.text("CONTROL EMPRESARIAL",61,35);pdf.setFontSize(10);pdf.setTextColor(71,85,105);pdf.text("Sistema de Control de Asistencia",61,44);pdf.setTextColor(255,255,255);pdf.setFont("helvetica","bold");pdf.setFontSize(25);pdf.text("MANUAL DEL SISTEMA",18,91);pdf.setFontSize(16);pdf.text("CONTROL DE ASISTENCIA",18,105);pdf.setFont("helvetica","normal");pdf.setFontSize(11);pdf.text("Guía completa, procedimientos y ejemplos prácticos",18,119);pdf.setDrawColor(147,197,253);pdf.line(18,132,188,132);pdf.setFontSize(10);pdf.text(`${SECCIONES_MANUAL.length} guías operativas`,18,146);pdf.text(`Generado: ${new Date().toLocaleString("es-PE")}`,18,154);pdf.setFillColor(37,99,235);pdf.roundedRect(18,174,174,48,5,5,"F");pdf.setFont("helvetica","bold");pdf.setFontSize(12);pdf.text("Incluye",27,188);pdf.setFont("helvetica","normal");pdf.setFontSize(9);pdf.text("• Explicación de cada módulo",27,199);pdf.text("• Procedimientos paso a paso",27,207);pdf.text("• Ejemplos prácticos y recomendaciones",27,215);
  nuevaPagina();texto("ÍNDICE GENERAL",18,[30,64,175],true);let categoria="";SECCIONES_MANUAL.forEach((s,i)=>{if(s.categoria!==categoria){categoria=s.categoria;texto(categoria.toUpperCase(),10,[37,99,235],true);}texto(`${i+1}. ${s.titulo}`,9,[51,65,85],false,4);});
  SECCIONES_MANUAL.forEach((s,indice)=>{nuevaPagina();texto(`${indice+1}. ${s.titulo}`,18,[30,64,175],true);texto(s.categoria.toUpperCase(),9,[37,99,235],true);texto(`Ruta: ${s.ruta}`,10,[71,85,105],true);texto(s.objetivo,11);texto("¿QUÉ PUEDES HACER AQUÍ?",11,[15,118,110],true);s.funciones.forEach(f=>texto(`• ${f}`,9,[51,65,85],false,3));texto("ANTES DE EMPEZAR",11,[124,58,237],true);s.requisitos.forEach(r=>texto(`• ${r}`,9,[51,65,85],false,3));texto("PROCEDIMIENTO DETALLADO",11,[37,99,235],true);s.pasos.forEach((p,i)=>texto(`${i+1}. ${p}`,9,[51,65,85],false,3));asegurar(20);pdf.setFillColor(239,246,255);pdf.roundedRect(margen,y-2,ancho,10,2,2,"F");y+=4;texto("EJEMPLO PRÁCTICO",11,[30,64,175],true);texto(`Situación: ${s.ejemplo.situacion}`,9);s.ejemplo.pasos.forEach((p,i)=>texto(`${i+1}. ${p}`,9,[51,65,85],false,3));texto(`Resultado: ${s.ejemplo.resultado}`,9,[22,101,52],true);if(s.advertencia){texto("IMPORTANTE",10,[185,28,28],true);texto(s.advertencia,9,[127,29,29]);}texto(`Resultado esperado: ${s.resultado}`,9,[22,101,52],true);texto(`Recomendación: ${s.consejo}`,9,[146,64,14]);});
  const total=pdf.getNumberOfPages();for(let i=2;i<=total;i++){pdf.setPage(i);pdf.setFontSize(8);pdf.setTextColor(100,116,139);pdf.text(`Manual de Control de Asistencia · Página ${i-1} de ${total-1}`,105,290,{align:"center"});}
  pdf.save(`manual-control-asistencia-${new Date().toISOString().slice(0,10)}.pdf`);
  await Swal.fire({icon:"success",title:"Manual descargado",text:"Se generó el PDF completo con procedimientos y ejemplos prácticos.",confirmButtonColor:"#2563eb"});
 }catch(error){await Swal.fire({icon:"error",title:"No se pudo generar el PDF",text:error.message||"Ocurrió un error inesperado.",confirmButtonColor:"#dc2626"});}
 finally{boton.disabled=false;boton.innerHTML=original;}
}
function encabezadoPdf(pdf,logo){pdf.setFillColor(30,64,175);pdf.rect(0,0,210,12,"F");if(logo)pdf.addImage(logo,"PNG",15,2,8,8);pdf.setTextColor(255,255,255);pdf.setFont("helvetica","bold");pdf.setFontSize(8);pdf.text("CONTROL EMPRESARIAL · MANUAL DEL SISTEMA",27,7.5);}
async function cargarLogoPdf(){try{const respuesta=await fetch("img/isotipo-color.png?v=20260820");if(!respuesta.ok)return null;const blob=await respuesta.blob();return await new Promise((resolve,reject)=>{const lector=new FileReader();lector.onload=()=>resolve(lector.result);lector.onerror=reject;lector.readAsDataURL(blob);});}catch(error){console.warn("No se pudo incluir el logo en el PDF:",error);return null;}}
