const {onCall,HttpsError}=require("firebase-functions/v2/https");
const {initializeApp}=require("firebase-admin/app");
const {getAuth}=require("firebase-admin/auth");
const {getFirestore,FieldValue,Timestamp}=require("firebase-admin/firestore");
const {generateRegistrationOptions,verifyRegistrationResponse,generateAuthenticationOptions,verifyAuthenticationResponse}=require("@simplewebauthn/server");
const crypto=require("crypto");
initializeApp();const db=getFirestore();

const REGION="us-central1";
const RP_NAME="Control de Asistencia";
const RP_ID=process.env.WEBAUTHN_RP_ID||"zavalachumpitazoscar.github.io";
const ORIGIN=process.env.WEBAUTHN_ORIGIN||"https://zavalachumpitazoscar.github.io";
const BASE_URL=process.env.PUBLIC_BASE_URL||`${ORIGIN}/control-asistencia`;
const SECUENCIA=["ENTRADA","INICIO_ALMUERZO","FIN_ALMUERZO","SALIDA"];

exports.invitarColaboradorMovil=callableAdmin(async({data,admin})=>{
  const colaboradorId=texto(data.colaboradorId);const ref=db.doc(`colaboradores/${colaboradorId}`),snap=await ref.get();
  if(!snap.exists||snap.data().empresaId!==admin.empresaId)throw new HttpsError("not-found","No se encontró el colaborador.");
  const c=snap.data(),correo=texto(c.contacto?.correo||c.correo).toLowerCase();if(!correo)throw new HttpsError("failed-precondition","El colaborador no tiene correo electrónico.");
  let usuario;try{usuario=await getAuth().getUserByEmail(correo);}catch(e){if(e.code!=="auth/user-not-found")throw e;usuario=await getAuth().createUser({email:correo,emailVerified:false,password:crypto.randomBytes(24).toString("base64url"),displayName:nombre(c),disabled:false});}
  await getAuth().setCustomUserClaims(usuario.uid,{tipo:"COLABORADOR_MOVIL",empresaId:admin.empresaId,colaboradorId});
  const acceso={empresaId:admin.empresaId,colaboradorId,usuarioId:usuario.uid,correo,nombre:nombre(c),estado:"ESPERANDO_DISPOSITIVO",actualizadoEn:FieldValue.serverTimestamp(),actualizadoPor:admin.uid};
  await Promise.all([db.doc(`accesosMoviles/${colaboradorId}`).set({...acceso,creadoEn:FieldValue.serverTimestamp()},{merge:true}),db.doc(`usuariosMoviles/${usuario.uid}`).set({...acceso,documento:documento(c),sucursalId:c.organizacion?.sucursalId||null,sucursal:c.organizacion?.sucursal||"",areaId:c.organizacion?.areaId||null,area:c.organizacion?.area||"",subareaId:c.organizacion?.subareaId||null,subarea:c.organizacion?.subarea||""},{merge:true})]);
  const enlace=await getAuth().generatePasswordResetLink(correo,{url:`${BASE_URL}/movil.html`,handleCodeInApp:false});
  await db.collection("mail").add({to:[correo],message:{subject:"Activa tu marcación móvil",html:`<div style="font-family:Arial;max-width:560px;margin:auto"><h2>Marcación móvil habilitada</h2><p>Hola ${escapeHtml(nombre(c))}, tu empresa habilitó el acceso al portal de marcación móvil.</p><p><a style="display:inline-block;padding:12px 18px;background:#2563eb;color:#fff;text-decoration:none;border-radius:8px" href="${enlace}">Crear contraseña e ingresar</a></p><p>Después del primer acceso, solicita la autorización de tu celular.</p></div>`},empresaId:admin.empresaId,tipo:"INVITACION_MARCACION_MOVIL",creadoEn:FieldValue.serverTimestamp()});
  return {ok:true,correo};
});

exports.solicitarDispositivoMovil=callableMovil(async({data,movil})=>{
  const dispositivoId=validarDispositivo(data.dispositivoId),id=`${movil.uid}_${dispositivoId}`;
  await db.doc(`solicitudesDispositivoMovil/${id}`).set({empresaId:movil.empresaId,colaboradorId:movil.colaboradorId,usuarioId:movil.uid,dispositivoId,dispositivo:sanitizarDispositivo(data.dispositivo),estado:"PENDIENTE",solicitadoEn:FieldValue.serverTimestamp()},{merge:true});
  await db.doc(`accesosMoviles/${movil.colaboradorId}`).set({estado:"PENDIENTE_AUTORIZACION",actualizadoEn:FieldValue.serverTimestamp()},{merge:true});
  return {ok:true};
});

exports.autorizarDispositivoMovil=callableAdmin(async({data,admin})=>{
  const ref=db.doc(`solicitudesDispositivoMovil/${texto(data.solicitudId)}`),snap=await ref.get();if(!snap.exists||snap.data().empresaId!==admin.empresaId)throw new HttpsError("not-found","Solicitud no encontrada.");const s=snap.data();
  const batch=db.batch();batch.update(ref,{estado:"AUTORIZADO",autorizadoEn:FieldValue.serverTimestamp(),autorizadoPor:admin.uid});batch.set(db.doc(`accesosMoviles/${s.colaboradorId}`),{estado:"AUTORIZADO",dispositivoAutorizadoId:s.dispositivoId,dispositivo:s.dispositivo,credencialRegistrada:false,actualizadoEn:FieldValue.serverTimestamp(),actualizadoPor:admin.uid},{merge:true});batch.set(db.doc(`usuariosMoviles/${s.usuarioId}`),{estado:"AUTORIZADO",dispositivoAutorizadoId:s.dispositivoId,dispositivo:s.dispositivo,actualizadoEn:FieldValue.serverTimestamp()},{merge:true});await batch.commit();return {ok:true};
});

exports.rechazarDispositivoMovil=callableAdmin(async({data,admin})=>{const ref=db.doc(`solicitudesDispositivoMovil/${texto(data.solicitudId)}`),s=await ref.get();if(!s.exists||s.data().empresaId!==admin.empresaId)throw new HttpsError("not-found","Solicitud no encontrada.");await ref.update({estado:"RECHAZADO",decididoEn:FieldValue.serverTimestamp(),decididoPor:admin.uid});return {ok:true};});
exports.revocarAccesoMovil=callableAdmin(async({data,admin})=>{const colaboradorId=texto(data.colaboradorId),ref=db.doc(`accesosMoviles/${colaboradorId}`),s=await ref.get();if(!s.exists||s.data().empresaId!==admin.empresaId)throw new HttpsError("not-found","Acceso no encontrado.");const a=s.data();await Promise.all([ref.set({estado:"BLOQUEADO",dispositivoAutorizadoId:null,credencialRegistrada:false,revocadoEn:FieldValue.serverTimestamp(),revocadoPor:admin.uid},{merge:true}),db.doc(`usuariosMoviles/${a.usuarioId}`).set({estado:"BLOQUEADO",dispositivoAutorizadoId:null},{merge:true}),getAuth().revokeRefreshTokens(a.usuarioId)]);return {ok:true};});

exports.guardarGeocercaMovil=callableAdmin(async({data,admin})=>{const id=texto(data.sucursalId),ref=db.doc(`sucursales/${id}`),s=await ref.get();if(!s.exists||s.data().empresaId!==admin.empresaId)throw new HttpsError("not-found","Sucursal no encontrada.");const lat=numero(data.latitud,-90,90),lng=numero(data.longitud,-180,180),radio=numero(data.radioMetros,20,5000);await ref.set({geocercaMovil:{latitud:lat,longitud:lng,radioMetros:radio,actualizadoEn:FieldValue.serverTimestamp(),actualizadoPor:admin.uid}},{merge:true});return {ok:true};});

exports.estadoPortalMovil=callableMovil(async({data,movil})=>{
  const dispositivoId=validarDispositivo(data.dispositivoId),[u,a]=await Promise.all([db.doc(`usuariosMoviles/${movil.uid}`).get(),db.doc(`accesosMoviles/${movil.colaboradorId}`).get()]);if(!u.exists||!a.exists)return {estadoAcceso:"NO_HABILITADO"};const perfil=u.data(),acceso=a.data();
  const solicitud=await db.doc(`solicitudesDispositivoMovil/${movil.uid}_${dispositivoId}`).get();const autorizado=acceso.estado==="AUTORIZADO"&&acceso.dispositivoAutorizadoId===dispositivoId;
  const hoy=fechaLima(new Date()),marcas=await db.collection("marcaciones").where("empresaId","==",movil.empresaId).where("colaboradorId","==",movil.colaboradorId).where("fecha","==",hoy).get();const lista=marcas.docs.map(d=>d.data()).filter(m=>SECUENCIA.includes(m.tipo)).sort((x,y)=>String(x.hora).localeCompare(String(y.hora)));
  return {estadoAcceso:acceso.estado,estadoDispositivo:autorizado?"AUTORIZADO":solicitud.exists&&solicitud.data().estado==="PENDIENTE"?"PENDIENTE":"NO_AUTORIZADO",credencialRegistrada:Boolean(acceso.credencialRegistrada&&acceso.credentialId),nombre:perfil.nombre,sucursal:perfil.sucursal||"",area:perfil.area||"",marcacionesHoy:lista.map(m=>({tipo:m.tipo,hora:m.hora})),siguienteMarcacion:SECUENCIA[lista.length]||null,horaServidor:new Date().toISOString()};
});

exports.iniciarRegistroWebAuthnMovil=callableMovil(async({data,movil})=>{
  const acceso=await accesoAutorizado(movil,data.dispositivoId);const opciones=await generateRegistrationOptions({rpName:RP_NAME,rpID:RP_ID,userName:movil.email,userDisplayName:acceso.nombre||movil.email,attestationType:"none",authenticatorSelection:{residentKey:"preferred",userVerification:"required"},excludeCredentials:acceso.credentialId?[{id:acceso.credentialId}]:[]});
  await db.doc(`desafiosMoviles/${movil.uid}`).set({tipo:"REGISTRO",challenge:opciones.challenge,dispositivoId:data.dispositivoId,expiraEn:Timestamp.fromMillis(Date.now()+300000)});return opciones;
});

exports.finalizarRegistroWebAuthnMovil=callableMovil(async({data,movil})=>{
  const acceso=await accesoAutorizado(movil,data.dispositivoId),desafio=await desafioValido(movil.uid,"REGISTRO",data.dispositivoId);const verificacion=await verifyRegistrationResponse({response:data.credencial,expectedChallenge:desafio.challenge,expectedOrigin:ORIGIN,expectedRPID:RP_ID,requireUserVerification:true});if(!verificacion.verified)throw new HttpsError("permission-denied","No se verificó el dispositivo.");const r=verificacion.registrationInfo.credential;
  await db.doc(`accesosMoviles/${movil.colaboradorId}`).set({credentialId:r.id,credentialPublicKey:Buffer.from(r.publicKey).toString("base64url"),credentialCounter:r.counter,credentialTransports:data.credencial.response?.transports||[],credencialRegistrada:true,credencialRegistradaEn:FieldValue.serverTimestamp(),estado:"AUTORIZADO"},{merge:true});await db.doc(`desafiosMoviles/${movil.uid}`).delete();return {ok:true};
});

exports.iniciarAutenticacionWebAuthnMovil=callableMovil(async({data,movil})=>{const acceso=await accesoAutorizado(movil,data.dispositivoId);if(!acceso.credentialId)throw new HttpsError("failed-precondition","Falta registrar la seguridad del dispositivo.");const opciones=await generateAuthenticationOptions({rpID:RP_ID,userVerification:"required",allowCredentials:[{id:acceso.credentialId,transports:acceso.credentialTransports||[]} ]});await db.doc(`desafiosMoviles/${movil.uid}`).set({tipo:"AUTENTICACION",challenge:opciones.challenge,dispositivoId:data.dispositivoId,tipoMarcacion:texto(data.tipo),expiraEn:Timestamp.fromMillis(Date.now()+180000)});return opciones;});

exports.registrarMarcacionMovil=callableMovil(async({data,movil})=>{
  const tipo=texto(data.tipo);if(!SECUENCIA.includes(tipo))throw new HttpsError("invalid-argument","Tipo de marcación inválido.");const acceso=await accesoAutorizado(movil,data.dispositivoId),desafio=await desafioValido(movil.uid,"AUTENTICACION",data.dispositivoId);if(desafio.tipoMarcacion!==tipo)throw new HttpsError("permission-denied","La solicitud de marcación no coincide.");
  const autenticador={credentialID:acceso.credentialId,credentialPublicKey:Buffer.from(acceso.credentialPublicKey,"base64url"),counter:Number(acceso.credentialCounter)||0,transports:acceso.credentialTransports||[]};const v=await verifyAuthenticationResponse({response:data.credencial,expectedChallenge:desafio.challenge,expectedOrigin:ORIGIN,expectedRPID:RP_ID,credential:autenticador,requireUserVerification:true});if(!v.verified)throw new HttpsError("permission-denied","No se verificó la identidad en el dispositivo.");
  const ubicacion=validarUbicacion(data.ubicacion),perfil=(await db.doc(`usuariosMoviles/${movil.uid}`).get()).data(),sucursal=perfil.sucursalId?await db.doc(`sucursales/${perfil.sucursalId}`).get():null;if(!sucursal?.exists||!sucursal.data().geocercaMovil)throw new HttpsError("failed-precondition","La empresa aún no configuró el perímetro de la sucursal.");const geo=sucursal.data().geocercaMovil,distancia=distanciaMetros(ubicacion.latitud,ubicacion.longitud,geo.latitud,geo.longitud);if(ubicacion.precisionMetros>150)throw new HttpsError("failed-precondition","La precisión del GPS es insuficiente. Activa la ubicación precisa.");if(distancia>geo.radioMetros+ubicacion.precisionMetros)throw new HttpsError("permission-denied",`Estás fuera del perímetro autorizado (${Math.round(distancia)} m).`);
  if(acceso.ultimaUbicacion&&acceso.ultimaMarcacionEn?.toMillis){const segundos=Math.max(1,(Date.now()-acceso.ultimaMarcacionEn.toMillis())/1000),recorrido=distanciaMetros(acceso.ultimaUbicacion.latitud,acceso.ultimaUbicacion.longitud,ubicacion.latitud,ubicacion.longitud),velocidadKmh=recorrido/segundos*3.6;if(recorrido>2000&&velocidadKmh>250)throw new HttpsError("permission-denied","La ubicación presenta un desplazamiento imposible. Marcación bloqueada para revisión.");}
  const ahora=new Date(),fecha=fechaLima(ahora),hora=horaLima(ahora),marcas=await db.collection("marcaciones").where("empresaId","==",movil.empresaId).where("colaboradorId","==",movil.colaboradorId).where("fecha","==",fecha).get(),orden=marcas.docs.map(d=>d.data()).filter(m=>SECUENCIA.includes(m.tipo)).sort((a,b)=>String(a.hora).localeCompare(String(b.hora))),esperada=SECUENCIA[orden.length];if(!esperada)throw new HttpsError("failed-precondition","La jornada móvil ya tiene sus cuatro marcaciones.");if(tipo!==esperada)throw new HttpsError("failed-precondition",`La siguiente marcación permitida es ${esperada.replaceAll("_"," ")}.`);
  const id=[movil.empresaId,movil.colaboradorId,fecha,tipo].join("_");await db.doc(`marcaciones/${id}`).create({empresaId:movil.empresaId,colaboradorId:movil.colaboradorId,colaboradorNombre:perfil.nombre,colaboradorDocumento:perfil.documento,fecha,hora,fechaHora:FieldValue.serverTimestamp(),fechaHoraISO:ahora.toISOString(),tipo,tipoOriginal:tipo,tipoInterpretado:tipo,origen:"MARCACION_MOVIL",estado:"VALIDA",dispositivoId:data.dispositivoId,credentialId:acceso.credentialId,ubicacion:{...ubicacion,distanciaSucursalMetros:Math.round(distancia),radioAutorizadoMetros:geo.radioMetros,sucursalId:perfil.sucursalId},riesgos:{ubicacionFueraPerimetro:false,precisionInsuficiente:false,rootNoVerificableEnWeb:true},creadoPor:movil.uid,fechaCreacion:FieldValue.serverTimestamp()});await Promise.all([db.doc(`accesosMoviles/${movil.colaboradorId}`).set({credentialCounter:v.authenticationInfo.newCounter,ultimaMarcacionEn:FieldValue.serverTimestamp(),ultimaUbicacion:{latitud:ubicacion.latitud,longitud:ubicacion.longitud}},{merge:true}),db.doc(`desafiosMoviles/${movil.uid}`).delete()]);return {ok:true,fecha,hora};
});

function callableAdmin(handler){return onCall({region:REGION,enforceAppCheck:false},async req=>{if(!req.auth)throw new HttpsError("unauthenticated","Debes iniciar sesión.");const p=await db.doc(`usuarios/${req.auth.uid}`).get();if(!p.exists)throw new HttpsError("permission-denied","Perfil administrativo no encontrado.");const d=p.data(),rol=String(d.rol||"").toUpperCase();if(!/ADMIN|PROPIET|GERENT/.test(rol))throw new HttpsError("permission-denied","No tienes permiso para esta operación.");return handler({...req,admin:{uid:req.auth.uid,empresaId:d.empresaId,rol}});});}
function callableMovil(handler){return onCall({region:REGION,enforceAppCheck:false},async req=>{if(!req.auth)throw new HttpsError("unauthenticated","Debes iniciar sesión.");const p=await db.doc(`usuariosMoviles/${req.auth.uid}`).get();if(!p.exists)throw new HttpsError("permission-denied","Acceso móvil no habilitado.");const d=p.data();return handler({...req,movil:{uid:req.auth.uid,email:req.auth.token.email||d.correo,empresaId:d.empresaId,colaboradorId:d.colaboradorId}});});}
async function accesoAutorizado(movil,dispositivoId){const id=validarDispositivo(dispositivoId),s=await db.doc(`accesosMoviles/${movil.colaboradorId}`).get();if(!s.exists||s.data().estado!=="AUTORIZADO"||s.data().dispositivoAutorizadoId!==id)throw new HttpsError("permission-denied","Este dispositivo no está autorizado.");return s.data();}
async function desafioValido(uid,tipo,dispositivoId){const s=await db.doc(`desafiosMoviles/${uid}`).get();if(!s.exists||s.data().tipo!==tipo||s.data().dispositivoId!==dispositivoId||s.data().expiraEn.toMillis()<Date.now())throw new HttpsError("deadline-exceeded","La validación expiró. Intenta nuevamente.");return s.data();}
function validarDispositivo(v){const x=texto(v);if(!/^[a-zA-Z0-9_-]{20,100}$/.test(x))throw new HttpsError("invalid-argument","Identificador de dispositivo inválido.");return x;}function validarUbicacion(u){if(!u)throw new HttpsError("invalid-argument","Ubicación obligatoria.");return {latitud:numero(u.latitud,-90,90),longitud:numero(u.longitud,-180,180),precisionMetros:numero(u.precisionMetros,0,5000),altitud:Number.isFinite(Number(u.altitud))?Number(u.altitud):null,obtenidaEn:texto(u.obtenidaEn)};}function sanitizarDispositivo(d={}){return Object.fromEntries(["descripcion","plataforma","navegador","idioma","zonaHoraria","pantalla"].map(k=>[k,texto(d[k]).slice(0,k==="navegador"?500:120)]));}function numero(v,min,max){const n=Number(v);if(!Number.isFinite(n)||n<min||n>max)throw new HttpsError("invalid-argument","Valor numérico fuera de rango.");return n;}function texto(v){return String(v||"").trim();}function nombre(c){return [c.datosPersonales?.nombres||c.nombres,c.datosPersonales?.apellidos||c.apellidos].filter(Boolean).join(" ")||"Colaborador";}function documento(c){return c.documento?.numero||c.numeroDocumento||c.dni||"";}function fechaLima(d){return new Intl.DateTimeFormat("en-CA",{timeZone:"America/Lima",year:"numeric",month:"2-digit",day:"2-digit"}).format(d);}function horaLima(d){return new Intl.DateTimeFormat("es-PE",{timeZone:"America/Lima",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(d);}function distanciaMetros(a,b,c,d){const r=6371000,p=x=>x*Math.PI/180,dp=p(c-a),dl=p(d-b),q=Math.sin(dp/2)**2+Math.cos(p(a))*Math.cos(p(c))*Math.sin(dl/2)**2;return 2*r*Math.atan2(Math.sqrt(q),Math.sqrt(1-q));}function escapeHtml(v){return texto(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]);}
